#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Gallery Infinite Scroll Fix

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 012-gallery-issues"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Get project root (relative to this script)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

echo "Project root: $PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=60
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

cd "$PROJECT_ROOT"

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing npm dependencies...${NC}"
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Kill any existing process on port 3000
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo -e "${YELLOW}Killing existing process on port 3000${NC}"
    kill $(lsof -Pi :3000 -sTCP:LISTEN -t) 2>/dev/null || true
    sleep 2
fi

# Start the Next.js dev server in background
npm run dev &
DEV_PID=$!

# Wait for the server to be ready
wait_for_service 3000 "Next.js Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo "  Gallery:   http://localhost:3000/gallery"
echo ""
echo "Files to modify:"
echo "  - src/features/shot-creator/store/unified-gallery-store.ts"
echo ""
echo "To stop the server, run: kill $DEV_PID"
echo ""
echo "========================================"
