#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Install dependencies (triggers Husky setup)
echo "Installing dependencies..."
npm install

# Start Next.js development server
echo "Starting Next.js development server..."
npm run dev &
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js:  http://localhost:3000"
echo ""
echo "Linting Infrastructure:"
echo "  - Pre-commit hooks installed via Husky"
echo "  - lint-staged configured to run ESLint on staged files"
echo "  - VS Code auto-fix on save enabled"
echo ""
echo "Useful commands:"
echo "  npm run lint       - Run ESLint"
echo "  npm run build      - Build for production"
echo "  git commit         - Will trigger pre-commit ESLint check"
echo ""
