#!/bin/bash

# Auto-Build Environment Setup
# Spec: 003 - Audit Storyboard Functionality
# Generated by Planner Agent

set -e

echo "========================================"
echo "Storyboard Audit - Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to project root
cd "$(dirname "$0")/../../.."

echo ""
echo "Project Root: $(pwd)"
echo ""

# Check for .env.local
if [ ! -f ".env.local" ]; then
    echo -e "${RED}Warning: .env.local not found${NC}"
    echo "The following environment variables are required:"
    echo "  - NEXT_PUBLIC_SUPABASE_URL"
    echo "  - NEXT_PUBLIC_SUPABASE_ANON_KEY"
    echo "  - OPENROUTER_API_KEY (for LLM features)"
    echo "  - REPLICATE_API_TOKEN (for image generation)"
    echo ""
fi

# Install dependencies if node_modules doesn't exist
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &
DEV_PID=$!

# Wait for dev server
wait_for_service 3000 "Next.js"

# ============================================
# VERIFY STORYBOARD PAGE
# ============================================

echo ""
echo "Verifying storyboard test page..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/test-storyboard)

if [ "$HTTP_CODE" = "200" ]; then
    echo -e "${GREEN}Storyboard test page accessible (HTTP $HTTP_CODE)${NC}"
else
    echo -e "${YELLOW}Warning: Storyboard page returned HTTP $HTTP_CODE${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Audit!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main App:      http://localhost:3000"
echo "  Storyboard:    http://localhost:3000/test-storyboard"
echo ""
echo "Audit Steps:"
echo "  1. Run E2E tests: npx playwright test tests/storyboard.spec.ts"
echo "  2. Open browser to test page and inspect manually"
echo "  3. Check browser console for errors"
echo "  4. Document all findings in AUDIT_REPORT.md"
echo ""
echo "Press Ctrl+C to stop the dev server when done."
echo ""

# Wait for the dev server
wait $DEV_PID
