#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Storybook Feature Audit

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Change to project directory
cd "$(dirname "$0")/../../.."

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# ============================================
# CHECK ENVIRONMENT
# ============================================

echo ""
echo "Checking environment variables..."

if [ ! -f ".env.local" ]; then
    echo -e "${RED}ERROR: .env.local file not found${NC}"
    echo "Please create .env.local with required environment variables"
    exit 1
fi

# Check for required variables
REQUIRED_VARS=("NEXT_PUBLIC_SUPABASE_URL" "NEXT_PUBLIC_SUPABASE_ANON_KEY" "REPLICATE_API_TOKEN" "ELEVENLABS_API_KEY")

for var in "${REQUIRED_VARS[@]}"; do
    if ! grep -q "^${var}=" .env.local; then
        echo -e "${YELLOW}WARNING: ${var} may not be set in .env.local${NC}"
    fi
done

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."

# Kill any existing process on port 3000
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    echo "Port 3000 in use, stopping existing process..."
    kill $(lsof -Pi :3000 -sTCP:LISTEN -t) 2>/dev/null || true
    sleep 2
fi

# Start development server in background
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Storybook Investigation:"
echo "  - Navigate to Storybook feature via sidebar"
echo "  - Test image upload in Character Setup step"
echo "  - Test character sheet generation in Characters step"
echo "  - Test narration in Preview step"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for background processes
wait $DEV_PID
