/**
 * Wardrobe Wildcards
 * 45 wildcards: 5 categories × 3 shot sizes × 3 genders
 *
 * Categories: street, lux, edge, sport, casual
 * Shot sizes: close (chest up), mid (waist up), full (head to toe)
 * Genders: male, female, unisex
 *
 * Every entry starts with "wearing" and describes ONLY clothing.
 * No accessories (jewelry, bags, watches, chains). No hairstyles.
 */

export interface WardrobeWildcard {
  name: string
  category: string
  description: string
  entries: string[]
}

// =============================================================================
// STREET — urban/streetwear
// =============================================================================

const STREET_WILDCARDS: WardrobeWildcard[] = [
  {
    name: 'close_male_street',
    category: 'wardrobe-street',
    description: 'Male streetwear, chest up — hoodies, graphic tees, layered urban tops',
    entries: [
      'wearing an oversized black Nike hoodie with a bold white swoosh, hood draped casually',
      'wearing a vintage Stussy graphic crewneck in washed olive over a white thermal undershirt',
      'wearing a black Carhartt WIP beanie and a heavyweight Pro Club white tee under a quilted black vest',
      'wearing a Champion reverse-weave hoodie in heather gray with a small embroidered C logo on the chest',
      'wearing a North Face black puffer vest over a dark green long-sleeve waffle-knit thermal',
      'wearing a Supreme box logo hoodie in navy blue with a crisp white tee visible underneath',
      'wearing a BAPE camo hoodie in green and brown, zip-up front partially open over a black tee',
      'wearing a Palace tri-ferg graphic tee in white under a plaid flannel shirt in red and black, unbuttoned',
      'wearing a black Nike tech fleece pullover hoodie with a matte black zip at the collar',
      'wearing a washed gray Hanes Beefy tee under a black leather-sleeve varsity jacket with chenille patches',
      'wearing a dark olive Dickies Eisenhower jacket with a corduroy collar over a plain white crewneck tee',
      'wearing a brown Carhartt active jacket with a quilted lining over a cream thermal henley',
      'wearing a color-blocked Puma windbreaker in teal and purple over a simple black crewneck',
      'wearing a vintage Karl Kani oversized denim jacket with embroidered branding over a black turtleneck',
      'wearing a washed black oversized hoodie under a sleeveless denim vest with embroidered back panel',
    ],
  },
  {
    name: 'close_female_street',
    category: 'wardrobe-street',
    description: 'Female streetwear, chest up — crop tops, oversized hoodies, layered urban looks',
    entries: [
      'wearing a cropped Nike swoosh hoodie in baby blue with a white sports bra visible underneath',
      'wearing an oversized vintage Champion crewneck in dusty pink, slipped off one shoulder',
      'wearing a fitted Adidas three-stripe crop top in black with a sheer mesh panel at the neckline',
      'wearing a Stussy oversized graphic tee in white, knotted at the front over a black tube top',
      'wearing a North Face cropped puffer in matte black over a ribbed white turtleneck',
      'wearing a BAPE camo print zip-up hoodie over a fitted black tank top',
      'wearing a vintage Nike windbreaker in purple and teal, zipped halfway over a white crop tee',
      'wearing a Supreme box logo tee in red tucked loosely under a plaid flannel in green and navy',
      'wearing a Jordan brand cropped hoodie in cement gray with embroidered Jumpman logo',
      'wearing a Carhartt WIP canvas chore jacket in tan over a fitted black ribbed mock-neck top',
      'wearing a Palace graphic long-sleeve in lavender over a white turtleneck layered underneath',
      'wearing an oversized denim jacket in light wash with patches and pins over a black crop top',
      'wearing a color-blocked Puma track jacket in coral and cream, zipped to the chest',
      'wearing a fitted Champion sports bra top in deep burgundy under an open plaid flannel in gray',
      'wearing a vintage Fila cropped crewneck in navy with the classic red and white logo on the chest',
    ],
  },
  {
    name: 'close_unisex_street',
    category: 'wardrobe-street',
    description: 'Unisex streetwear, chest up — oversized, gender-neutral urban layers',
    entries: [
      'wearing an oversized washed black hoodie with raw-edge hem over a long white tee',
      'wearing a Carhartt WIP chore coat in duck brown over a heather gray crewneck sweatshirt',
      'wearing a vintage Nike ACG fleece pullover in forest green with a half-zip collar',
      'wearing an oversized Dickies work shirt in charcoal, buttoned halfway over a plain black tee',
      'wearing a quilted black liner jacket over a heavyweight ash gray crewneck',
      'wearing a North Face Denali fleece in black with a high collar zipped to the chin',
      'wearing an oversized Champion hoodie in Oxford gray layered under a black canvas vest',
      'wearing a plaid flannel in navy and brown, fully open over a vintage band tee in faded black',
      'wearing a Stussy embroidered crewneck in cream over a long-sleeve striped tee in black and white',
      'wearing a patchwork denim jacket with mixed washes and visible stitching over a black hoodie',
      'wearing a corduroy overshirt in burnt orange, buttoned up with sleeves rolled to the elbows',
      'wearing a washed olive military surplus jacket with multiple pockets over a white thermal',
      'wearing a black mock-neck long-sleeve under an unbuttoned bowling shirt in green and cream',
      'wearing an oversized graphic tee in off-white with abstract print under a black zip-up hoodie',
      'wearing a heavyweight French terry crewneck in slate blue with ribbed cuffs and collar',
    ],
  },
  {
    name: 'mid_male_street',
    category: 'wardrobe-street',
    description: 'Male streetwear, waist up — full upper body with waistline details',
    entries: [
      'wearing a black Nike tech fleece zip-up hoodie over a white tee, black joggers visible at the waist',
      'wearing a vintage Stussy graphic crewneck in olive tucked loosely into high-waisted dark cargo pants',
      'wearing an oversized Adidas Originals track jacket in navy with white triple stripes, matching track pants at the waist',
      'wearing a Carhartt WIP Detroit jacket in black rigid denim over a gray hoodie, dark Dickies pants at the waist',
      'wearing a North Face Nuptse puffer in matte black over a long white tee, baggy jeans visible from the hips',
      'wearing a Champion reverse-weave hoodie in forest green tucked behind a brown leather belt with silver buckle',
      'wearing a Supreme motion logo hoodie in black over a long white tee, dark denim waistband showing',
      'wearing a plaid flannel in red and black over a Pro Club white tee, Dickies 874 work pants at the waist',
      'wearing a BAPE shark hoodie in purple camo fully zipped, black joggers at the waist',
      'wearing a leather-sleeve varsity jacket in black and cream over a gray crewneck, dark jeans at the hips',
      'wearing a vintage Pelle Pelle leather jacket in brown over a black hoodie, baggy dark denim at the waist',
      'wearing a black denim trucker jacket with faux shearling collar over a striped long-sleeve, khaki chinos at the waist',
      'wearing a Puma T7 track jacket in burgundy with cream stripes, matching burgundy track pants visible at the waist',
      'wearing an oversized Palace graphic tee in white, tucked into high-waisted black cargo pants with a woven belt',
      'wearing a quilted black vest over a gray Nike crewneck, olive cargo pants visible at the waistline',
    ],
  },
  {
    name: 'mid_female_street',
    category: 'wardrobe-street',
    description: 'Female streetwear, waist up — crop layers, high-waisted bottoms visible',
    entries: [
      'wearing a cropped Nike hoodie in white with high-waisted baggy black cargo pants and a woven belt',
      'wearing an oversized vintage Champion crewneck in pink, knotted at the waist over dark denim mom jeans',
      'wearing a fitted Adidas crop top in black under an open flannel, high-waisted olive cargo pants at the hips',
      'wearing a Jordan brand hoodie in cement gray, unzipped over a black sports bra, gray sweats at the waist',
      'wearing a vintage oversized denim jacket over a white crop tee, high-waisted light wash jeans at the waist',
      'wearing a North Face cropped puffer in lilac over a black bodysuit, baggy vintage Levi\'s at the hips',
      'wearing a BAPE camo print crop hoodie, black high-waisted biker shorts visible at the waist',
      'wearing a Stussy graphic tee knotted at the front over high-waisted wide-leg black trousers',
      'wearing a fitted mock-neck crop top in black under a plaid overshirt, dark cargo pants at the waist',
      'wearing a Palace long-sleeve crop in lavender, matching oversized lavender sweats at the hips',
      'wearing a cropped denim vest with patches over a white tube top, baggy low-rise jeans at the waist',
      'wearing a Puma cropped track jacket in coral, high-waisted black leggings visible at the waistline',
      'wearing a fitted Champion sports bra in burgundy under an open oversized flannel, dark joggers at the hips',
      'wearing an oversized graphic tee dress belted at the waist with a black canvas belt',
      'wearing a cropped black bomber jacket over a ribbed white tank, high-waisted plaid pants at the waist',
    ],
  },
  {
    name: 'mid_unisex_street',
    category: 'wardrobe-street',
    description: 'Unisex streetwear, waist up — oversized, androgynous with waistline visible',
    entries: [
      'wearing an oversized washed black hoodie over a long white tee, dark baggy jeans at the waist',
      'wearing a Carhartt WIP chore coat in duck brown over a cream crewneck, dark work pants at the hips',
      'wearing a vintage Nike ACG half-zip fleece in forest green, black nylon pants at the waistline',
      'wearing an oversized Dickies work shirt in charcoal over a black tee, matching Dickies pants at the waist',
      'wearing a quilted liner jacket in matte black over a gray hoodie, olive cargos at the hips',
      'wearing a North Face Denali fleece in black, dark straight-leg jeans at the waist',
      'wearing a patchwork denim jacket over a black hoodie, wide-leg black pants at the hips',
      'wearing a corduroy overshirt in burnt orange over a white tee, tan chinos at the waistline',
      'wearing a military surplus jacket in olive over a thermal, dark fatigue pants at the waist',
      'wearing a bowling shirt in green and cream over a black mock-neck, relaxed black trousers at the hips',
      'wearing an oversized graphic crewneck in cream, tucked loosely into wide-leg black denim',
      'wearing a heavyweight French terry hoodie in slate blue, dark cargo pants at the waist',
      'wearing a black canvas chore jacket over a striped long-sleeve tee, brown carpenter pants at the hips',
      'wearing a washed denim overshirt in medium blue over a black tee, dark straight-leg pants at the waist',
      'wearing a fleece-lined flannel in gray and black, buttoned up, dark joggers at the hips',
    ],
  },
  {
    name: 'full_male_street',
    category: 'wardrobe-street',
    description: 'Male streetwear, head to toe — complete outfits with shoes',
    entries: [
      'wearing a black Nike tech fleece tracksuit with zip-up hoodie and slim joggers, white Air Force 1 Lows',
      'wearing an oversized Stussy graphic tee in olive, baggy dark wash jeans, and Nike Dunk Lows in panda colorway',
      'wearing a Carhartt WIP Detroit jacket in black over a gray hoodie, Dickies 874 work pants, and wheat Timberland 6-inch boots',
      'wearing a North Face Nuptse puffer in matte black, dark baggy jeans, and Jordan 4 Retros in cement gray',
      'wearing a Champion reverse-weave hoodie in forest green, khaki cargo pants, and New Balance 550s in white and green',
      'wearing a vintage Pelle Pelle leather jacket over a white tee, baggy black jeans, and classic white Nike Cortez',
      'wearing a Supreme box logo hoodie in navy, dark straight-leg jeans, and black-and-white Jordan 1 Highs',
      'wearing a plaid flannel in red and black over a Pro Club tee, Dickies double-knee pants in khaki, and Vans Old Skool in black',
      'wearing a leather-sleeve varsity jacket in black and cream, slim dark jeans, and Nike Air Max 90s in infrared',
      'wearing a BAPE shark hoodie in camo, black joggers, and Adidas Samba OGs in white and black',
      'wearing a quilted black vest over a gray crewneck, olive cargo pants, and Salomon XT-6 trail shoes in gray',
      'wearing a vintage Karl Kani denim jacket over a black tee, baggy blue jeans, and Reebok Club C 85s in white',
      'wearing a Puma T7 track jacket in burgundy with cream stripes, matching track pants, and Puma Suede Classics in black',
      'wearing an Adidas Originals track jacket in navy, matching pants with white stripes, and Stan Smith sneakers in white',
      'wearing a black bomber jacket over a long white tee, dark straight-leg cargos, and Converse Chuck 70 Highs in black',
    ],
  },
  {
    name: 'full_female_street',
    category: 'wardrobe-street',
    description: 'Female streetwear, head to toe — complete outfits with shoes',
    entries: [
      'wearing a cropped Nike hoodie in baby blue, high-waisted baggy jeans, and Air Jordan 1 Lows in mocha',
      'wearing an oversized Champion crewneck in dusty pink, black biker shorts, and Nike Dunk Lows in gray fog',
      'wearing a North Face cropped puffer in matte black, vintage straight-leg Levi\'s, and New Balance 530s in white and silver',
      'wearing a Stussy graphic tee knotted at the waist, wide-leg olive cargo pants, and Converse Chuck 70 Lows in cream',
      'wearing a vintage denim jacket with patches over a white crop top, baggy mom jeans, and Adidas Samba OGs in white',
      'wearing a plaid flannel in green and navy over a black tube top, low-rise baggy jeans, and Nike Air Max 97s in silver',
      'wearing a Jordan cropped hoodie in cement gray, matching gray sweats, and Jordan 4 Retros in off-white',
      'wearing a BAPE camo crop hoodie, black leggings, and Nike Air Force 1 Lows in triple white',
      'wearing a Carhartt WIP chore jacket in tan over a fitted black top, dark cargo pants, and Dr. Martens 1461 oxfords in black',
      'wearing a cropped Puma track jacket in coral, high-waisted black track pants, and Puma Speedcat OGs in red',
      'wearing an oversized graphic tee as a dress, belted at the waist, and chunky New Balance 2002R in rain cloud gray',
      'wearing a fitted mock-neck crop in black under a denim overshirt, wide-leg jeans, and Vans Old Skool in checkerboard',
      'wearing a Palace long-sleeve crop in lavender, matching oversized sweats, and Nike Blazer Mid 77s in white',
      'wearing a vintage Fila crewneck in navy, high-waisted light wash mom jeans, and Fila Disruptor 2s in white',
      'wearing a cropped black bomber over a ribbed white tank, plaid wide-leg pants, and Converse Run Star Hike platforms in black',
    ],
  },
  {
    name: 'full_unisex_street',
    category: 'wardrobe-street',
    description: 'Unisex streetwear, head to toe — gender-neutral complete outfits',
    entries: [
      'wearing an oversized washed black hoodie, wide-leg black carpenter pants, and Nike Air Force 1 Lows in white',
      'wearing a Carhartt WIP chore coat in duck brown, dark straight-leg jeans, and New Balance 990v5s in gray',
      'wearing a North Face Denali fleece in black, dark nylon cargo pants, and Salomon XT-6 trail shoes in black',
      'wearing a Dickies work shirt in charcoal over a black tee, matching Dickies 874 pants, and Vans Authentic in black',
      'wearing a quilted liner jacket over a gray hoodie, olive fatigue pants, and Clarks Wallabees in beeswax',
      'wearing a patchwork denim jacket over a black crewneck, wide-leg raw denim jeans, and Converse Chuck 70 Highs in black',
      'wearing a corduroy overshirt in burnt orange over a white tee, tan chinos, and Adidas Gazelles in navy',
      'wearing a military surplus jacket in olive, dark fatigue pants, and combat boots in matte black',
      'wearing a vintage Nike ACG fleece in forest green, black nylon pants, and ACG hiking boots in brown',
      'wearing an oversized graphic crewneck in cream, relaxed black jeans, and New Balance 2002R in cream',
      'wearing a canvas chore jacket in black over a striped tee, brown carpenter pants, and Red Wing Iron Rangers in amber',
      'wearing a fleece-lined flannel in gray and black, dark joggers, and Nike Air Max 90s in triple black',
      'wearing a heavyweight hoodie in slate blue, wide-leg olive pants, and Asics Gel-Kayano 14 in silver',
      'wearing a washed denim overshirt over a black tee, relaxed straight jeans, and Birkenstock Bostons in taupe suede',
      'wearing a black mock-neck under an open bowling shirt in green, relaxed trousers, and Adidas Samba OGs in black',
    ],
  },
]

// =============================================================================
// LUX — luxury/designer
// =============================================================================

const LUX_WILDCARDS: WardrobeWildcard[] = [
  {
    name: 'close_male_lux',
    category: 'wardrobe-lux',
    description: 'Male luxury fashion, chest up — designer tailoring and premium fabrics',
    entries: [
      'wearing a black cashmere turtleneck under a charcoal Tom Ford peak-lapel blazer',
      'wearing a Brunello Cucinelli oatmeal cable-knit cashmere sweater with a spread-collar white shirt underneath',
      'wearing a Prada black nylon and leather bomber jacket over a white cotton crewneck tee',
      'wearing a Louis Vuitton monogram-embossed denim jacket over a plain black mock-neck',
      'wearing a double-breasted navy Dior wool overcoat with a silk-lined shawl collar',
      'wearing a Gucci silk button-up shirt with a bold red and green horizontal stripe across the chest',
      'wearing a Versace baroque-print silk shirt in black and gold with a relaxed open collar',
      'wearing a YSL black velvet blazer with satin peak lapels over a sheer black silk shirt',
      'wearing a Fendi FF-logo knit sweater in cream and brown over a crisp white dress shirt',
      'wearing a Burberry classic check cashmere scarf over a black wool peacoat',
      'wearing a Zegna charcoal merino wool half-zip sweater over a light blue poplin shirt collar',
      'wearing a Moncler matte black down vest over a cream cashmere crewneck sweater',
      'wearing a Balenciaga oversized black wool topcoat with structured shoulders',
      'wearing a Loro Piana storm system jacket in navy over a fine-gauge gray turtleneck',
      'wearing an Hermès silk-blend knit polo in forest green with mother-of-pearl buttons',
    ],
  },
  {
    name: 'close_female_lux',
    category: 'wardrobe-lux',
    description: 'Female luxury fashion, chest up — designer blouses, blazers, elegant layers',
    entries: [
      'wearing a Chanel black tweed jacket with gold-button detailing and a white silk blouse underneath',
      'wearing a Dior Bar jacket in ivory wool with a nipped waist and satin bow at the collar',
      'wearing a Bottega Veneta cashmere turtleneck in deep chocolate brown, oversized and draped',
      'wearing a Gucci floral silk blouse in muted rose with a pussy-bow tie at the neck',
      'wearing a Max Mara camel hair double-breasted blazer over a cream silk camisole',
      'wearing a Prada black nylon crop jacket with a silver triangle logo at the chest',
      'wearing a Saint Laurent black leather blazer with padded shoulders over a sheer silk shell',
      'wearing a Valentino red crepe blouse with a dramatic ruffle collar and bishop sleeves',
      'wearing a Fendi brown FF-logo knit cardigan buttoned over a fitted white turtleneck',
      'wearing a Burberry trench-style cape in classic beige with the signature check lining visible at the collar',
      'wearing a Celine oversized black wool coat with minimal lapels and a hidden button front',
      'wearing a Versace Medusa-button black silk shirt with the collar open, structured shoulders',
      'wearing a Loro Piana baby cashmere wrap sweater in soft gray, draped elegantly over the shoulders',
      'wearing an Hermès silk twill scarf in orange and gold draped over a white cashmere turtleneck',
      'wearing a Miu Miu cropped embellished cardigan in pale blue with pearl-button details',
    ],
  },
  {
    name: 'close_unisex_lux',
    category: 'wardrobe-lux',
    description: 'Unisex luxury fashion, chest up — oversized designer pieces, gender-neutral elegance',
    entries: [
      'wearing a Bottega Veneta oversized intrecciato-pattern leather coat in dark espresso',
      'wearing a The Row black cashmere crewneck sweater with a clean, minimal silhouette',
      'wearing a Loro Piana storm system bomber jacket in navy over a cream cashmere tee',
      'wearing a Jil Sander oversized cotton shirt in stark white with a mandarin collar',
      'wearing a Lemaire twisted silk shirt in olive green with a draped asymmetric neckline',
      'wearing an Acne Studios oversized mohair sweater in dusty lilac with a crew neck',
      'wearing a Prada re-nylon puffer jacket in matte black, zipped high at the collar',
      'wearing a Zegna double-breasted cashmere overcoat in camel, structured and relaxed-fit',
      'wearing a Maison Margiela deconstructed blazer in charcoal with visible tacking stitches',
      'wearing a Tom Ford black cashmere zip-up knit jacket with ribbed cuffs and collar',
      'wearing a Hermès reversible leather blouson jacket in black and chocolate brown',
      'wearing a Celine oversized checked wool shirt jacket in beige and cream',
      'wearing a Brunello Cucinelli suede bomber jacket in taupe over a gray silk-blend tee',
      'wearing a Fear of God Essentials oversized hoodie in oatmeal under a structured wool topcoat in charcoal',
      'wearing a Balenciaga political logo hoodie in washed black under a structured camel overcoat',
    ],
  },
  {
    name: 'mid_male_lux',
    category: 'wardrobe-lux',
    description: 'Male luxury fashion, waist up — tailored designer pieces with trouser waistline',
    entries: [
      'wearing a Tom Ford charcoal wool suit jacket over a black mock-neck, slim dark trousers at the waist',
      'wearing a Brunello Cucinelli oatmeal cashmere sweater tucked into tobacco brown pleated wool trousers',
      'wearing a Gucci black leather bomber over a cream silk tee, dark tailored pants at the waistline',
      'wearing a Louis Vuitton denim jacket over a white tee, monogram-belted dark trousers at the hips',
      'wearing a Dior navy double-breasted blazer over a black turtleneck, charcoal wool trousers at the waist',
      'wearing a Prada nylon shirt jacket in midnight blue, black wool trousers with a leather belt at the waist',
      'wearing a Versace baroque silk shirt tucked into high-waisted black trousers with a gold Medusa belt buckle',
      'wearing a Zegna charcoal half-zip sweater over a white shirt, gray flannel trousers at the waist',
      'wearing a Moncler quilted down gilet in navy over a white dress shirt, dark chinos at the waistline',
      'wearing a Burberry trench coat in honey beige, dark wool trousers visible at the waist',
      'wearing a YSL black velvet blazer over a sheer silk shirt, slim black wool trousers at the hips',
      'wearing a Loro Piana suede bomber in chocolate over a cream knit, tan wool trousers at the waist',
      'wearing a Fendi FF-logo knit over dark brown leather trousers with a slim cut at the waist',
      'wearing a Balenciaga oversized black blazer over a white tee, wide-leg trousers at the hips',
      'wearing an Hermès leather blouson in black, dark navy wool trousers with a polished silver belt buckle',
    ],
  },
  {
    name: 'mid_female_lux',
    category: 'wardrobe-lux',
    description: 'Female luxury fashion, waist up — designer tops with skirt/trouser waistlines',
    entries: [
      'wearing a Chanel tweed jacket in blush pink over a white silk blouse, high-waisted black trousers at the waist',
      'wearing a Dior Bar jacket in ivory over a black camisole, a pleated midi skirt waistband visible',
      'wearing a Bottega Veneta leather shirt in deep brown, tucked into high-waisted cream trousers',
      'wearing a Gucci silk blouse in flora print tucked into a high-waisted black pencil skirt',
      'wearing a Max Mara camel hair coat, belted at the waist with a matching camel leather belt',
      'wearing a Saint Laurent black sequin blazer over a sheer shell, high-waisted leather pants at the hips',
      'wearing a Valentino red silk blouse, tucked into high-waisted black wide-leg trousers',
      'wearing a Prada nylon crop jacket, fitted black trousers with a high waist visible',
      'wearing a Fendi brown cardigan over a white turtleneck, high-waisted pleated culottes at the waist',
      'wearing a Celine black wool blazer with gold buttons, dark slim trousers at the waistline',
      'wearing a Burberry trench cape in beige, a belted black skirt visible at the waist',
      'wearing a Versace Medusa-button silk shirt, tucked into a high-waisted black bodycon skirt',
      'wearing a Loro Piana cashmere wrap sweater in pale gray, cream wool wide-leg trousers at the hips',
      'wearing a Miu Miu cropped cardigan in pale blue, a high-waisted pleated mini skirt at the waist',
      'wearing an Hermès orange silk scarf draped over a white blazer, dark navy trousers at the waist',
    ],
  },
  {
    name: 'mid_unisex_lux',
    category: 'wardrobe-lux',
    description: 'Unisex luxury fashion, waist up — oversized designer layers with waistline',
    entries: [
      'wearing a The Row oversized cashmere crewneck in black, wide-leg wool trousers at the waist',
      'wearing a Bottega Veneta leather coat in espresso, dark trousers visible at the hips',
      'wearing a Lemaire twisted shirt in olive, tucked loosely into high-waisted black cotton trousers',
      'wearing a Jil Sander oversized white shirt, belted with a thin black leather belt at the waist',
      'wearing an Acne Studios mohair sweater in lilac, dark relaxed-fit trousers at the hips',
      'wearing a Prada re-nylon jacket in black, matching nylon trousers at the waistline',
      'wearing a Celine checked shirt jacket in beige, dark straight-leg jeans at the waist',
      'wearing a Maison Margiela deconstructed blazer in gray, wide-leg black trousers at the hips',
      'wearing a Zegna cashmere overcoat in camel, dark flannel trousers at the waist',
      'wearing a Tom Ford zip-up knit in black, charcoal wool trousers at the waistline',
      'wearing a Fear of God Essentials hoodie in oatmeal under a structured coat, relaxed trousers at the hips',
      'wearing a Brunello Cucinelli suede bomber in taupe, cream linen trousers at the waist',
      'wearing a Loro Piana baby cashmere hoodie in navy, tan wool trousers at the waistline',
      'wearing a Hermès reversible leather jacket in black, dark slim trousers at the waist',
      'wearing a Balenciaga oversized blazer in black, wide-leg charcoal trousers at the hips',
    ],
  },
  {
    name: 'full_male_lux',
    category: 'wardrobe-lux',
    description: 'Male luxury fashion, head to toe — complete designer outfits with shoes',
    entries: [
      'wearing a Tom Ford charcoal wool suit with peak lapels over a black mock-neck, polished black leather oxford shoes',
      'wearing a Brunello Cucinelli oatmeal cashmere sweater, tobacco brown pleated trousers, and tan suede loafers',
      'wearing a Gucci black leather bomber over a white tee, dark tailored pants, and black Gucci Horsebit loafers',
      'wearing a Dior navy double-breasted overcoat over a black turtleneck, charcoal trousers, and black patent leather derbies',
      'wearing a Louis Vuitton monogram denim jacket, dark straight jeans, and LV Trainer sneakers in white and gray',
      'wearing a Prada nylon bomber in midnight blue, black wool trousers, and Prada Cloudbust sneakers in black',
      'wearing a Versace baroque silk shirt tucked into black trousers, and glossy black Versace chain-detail loafers',
      'wearing a Burberry trench in honey beige, dark wool trousers, and polished brown Chelsea boots',
      'wearing a Zegna charcoal half-zip over a white shirt, gray flannels, and dark brown suede chukka boots',
      'wearing a Moncler quilted gilet in navy over a white shirt, dark chinos, and white minimalist leather sneakers',
      'wearing a Loro Piana suede bomber in chocolate, cream trousers, and hand-stitched tan leather driving shoes',
      'wearing a Balenciaga oversized black blazer over a white tee, wide-leg trousers, and Triple S sneakers in gray',
      'wearing a YSL black velvet blazer over a silk shirt, slim trousers, and black pointed-toe Wyatt boots',
      'wearing a Fendi FF-logo knit, dark leather trousers, and Fendi Flow sneakers in brown and black',
      'wearing an Hermès black leather blouson, navy trousers, and polished black Hermès leather ankle boots',
    ],
  },
  {
    name: 'full_female_lux',
    category: 'wardrobe-lux',
    description: 'Female luxury fashion, head to toe — complete designer outfits with shoes',
    entries: [
      'wearing a Chanel tweed jacket in blush over a white silk blouse, black slim trousers, and beige slingback pumps',
      'wearing a Dior Bar jacket in ivory, a black pleated midi skirt, and black patent Dior J\'Adior slingbacks',
      'wearing a Bottega Veneta leather shirt in brown, cream wide-leg trousers, and brown intrecciato mules',
      'wearing a Gucci floral silk blouse, high-waisted black pencil skirt, and red Gucci Horsebit loafers',
      'wearing a Max Mara camel coat belted at the waist, dark trousers, and tan leather knee-high boots',
      'wearing a Saint Laurent black sequin blazer, leather skinny pants, and pointed-toe black stiletto ankle boots',
      'wearing a Valentino red silk blouse, black wide-leg trousers, and nude Rockstud pumps',
      'wearing a Prada nylon crop jacket, black fitted trousers, and chunky black Prada loafer platforms',
      'wearing a Celine black wool blazer, dark slim trousers, and Celine Triomphe canvas loafers in tan',
      'wearing a Burberry trench cape in beige, a black midi skirt, and Burberry check rain boots',
      'wearing a Versace silk shirt, black bodycon skirt, and gold-buckle Versace platform sandals',
      'wearing a Loro Piana cashmere wrap sweater in gray, cream wide-leg trousers, and suede ballet flats in tan',
      'wearing a Fendi brown cardigan, cream culottes, and Fendi Fendi-First heeled sandals in brown',
      'wearing a Miu Miu embellished cardigan in blue, a pleated mini skirt, and patent leather Mary Janes in black',
      'wearing an Hermès silk scarf over a white blazer, dark trousers, and Hermès Oran sandals in gold',
    ],
  },
  {
    name: 'full_unisex_lux',
    category: 'wardrobe-lux',
    description: 'Unisex luxury fashion, head to toe — gender-neutral designer outfits',
    entries: [
      'wearing a The Row black cashmere crewneck, wide-leg wool trousers, and black leather slide sandals',
      'wearing a Bottega Veneta leather coat in espresso, dark trousers, and brown lug-sole Chelsea boots',
      'wearing a Lemaire twisted shirt in olive, black cotton trousers, and cream canvas slip-on sneakers',
      'wearing a Jil Sander oversized white shirt, dark straight pants, and black leather platform derbies',
      'wearing an Acne Studios mohair sweater in lilac, relaxed black trousers, and white minimalist sneakers',
      'wearing a Prada re-nylon jacket and matching pants in black, with Prada Cloudbust sneakers',
      'wearing a Celine checked shirt jacket in beige, dark jeans, and tan suede desert boots',
      'wearing a Maison Margiela deconstructed blazer, wide-leg black trousers, and Tabi boots in black',
      'wearing a Zegna cashmere overcoat in camel, dark flannel trousers, and brown suede Chelsea boots',
      'wearing a Tom Ford black zip-up knit, charcoal trousers, and polished black leather loafers',
      'wearing a Fear of God Essentials hoodie under a structured coat, relaxed trousers, and Fear of God boat shoes in taupe',
      'wearing a Brunello Cucinelli suede bomber in taupe, cream linen trousers, and tan driving moccasins',
      'wearing a Loro Piana cashmere hoodie in navy, tan trousers, and suede open-back loafers in brown',
      'wearing a Hermès reversible leather jacket in black, dark trousers, and Hermès leather espadrilles',
      'wearing a Balenciaga oversized blazer, wide-leg trousers, and Defender sneakers in black',
    ],
  },
]

// =============================================================================
// EDGE — alternative/experimental/punk
// =============================================================================

const EDGE_WILDCARDS: WardrobeWildcard[] = [
  {
    name: 'close_male_edge',
    category: 'wardrobe-edge',
    description: 'Male alternative fashion, chest up — punk, deconstructed, dark avant-garde',
    entries: [
      'wearing a studded black leather motorcycle jacket over a faded vintage band tee with a torn collar',
      'wearing a Rick Owens draped hoodie in charcoal with an oversized industrial zipper at the neck',
      'wearing a deconstructed black denim jacket with raw frayed seams over a mesh long-sleeve shirt',
      'wearing a Comme des Garcons asymmetric patchwork blazer in black and charcoal',
      'wearing a black moto jacket with silver hardware and diagonal zipper over a distressed black tee',
      'wearing a Yohji Yamamoto oversized drape-front shirt in jet black with an irregular hemline',
      'wearing a shredded black tank top under a paint-splattered black denim vest with safety pins',
      'wearing a black turtleneck under a Vivienne Westwood deconstructed plaid blazer with raw edges',
      'wearing an Alexander McQueen skull-print silk shirt in black and silver, collar open',
      'wearing a harness-strap leather vest over a long-sleeve mesh top in black',
      'wearing a black oversized knit sweater with intentional holes and dropped shoulders',
      'wearing a bleach-splattered black hoodie with a raw-cut neckline and thumb holes',
      'wearing a black military-style jacket with silver spike studs along the shoulder epaulets',
      'wearing a black linen wrap shirt with an asymmetric front closure and mandarin collar',
      'wearing a distressed black crewneck with screen-printed gothic lettering and safety pin details',
    ],
  },
  {
    name: 'close_female_edge',
    category: 'wardrobe-edge',
    description: 'Female alternative fashion, chest up — punk, dark, deconstructed layers',
    entries: [
      'wearing a cropped leather moto jacket with silver studs over a torn black mesh top',
      'wearing a Rick Owens draped leather jacket in dark dust over a fitted black ribbed tank',
      'wearing a Vivienne Westwood tartan corset top with asymmetric draping and raw edges',
      'wearing a sheer black lace blouse with a high Victorian collar over a black bandeau',
      'wearing an Alexander McQueen structured leather jacket with exaggerated sharp shoulders',
      'wearing a Comme des Garcons deconstructed white shirt with intentional fraying and uneven hem',
      'wearing a cropped black PVC jacket with silver hardware over a distressed gray band tee',
      'wearing a Yohji Yamamoto oversized black wool blazer with a draped front and no closure',
      'wearing a black velvet choker-collar top with sheer sleeves and visible seam lines',
      'wearing a corset-style bustier top in black leather over a long-sleeve mesh shirt',
      'wearing a safety-pin detailed black denim jacket over a torn fishnet long-sleeve layer',
      'wearing a black silk slip top with raw-edge trim under an oversized distressed cardigan',
      'wearing a black latex-look crop top with a high neck under an open plaid flannel with bleach stains',
      'wearing a deconstructed black blazer with one lapel removed, over a sheer black turtleneck',
      'wearing an oversized black band hoodie with cut-off sleeves, raw edges showing frayed threads',
    ],
  },
  {
    name: 'close_unisex_edge',
    category: 'wardrobe-edge',
    description: 'Unisex alternative fashion, chest up — dark, androgynous, deconstructed',
    entries: [
      'wearing a Rick Owens oversized leather jacket in black with a dramatic asymmetric zipper',
      'wearing a Comme des Garcons patchwork shirt in mismatched black fabrics with raw seams',
      'wearing a black oversized hoodie with bleach-drip stains and a raw-cut neckline',
      'wearing a Yohji Yamamoto oversized linen shirt in jet black with an irregular hem',
      'wearing a deconstructed black trench coat with exposed lining and frayed lapels',
      'wearing a black mesh long-sleeve shirt under a distressed leather vest with painted back panel',
      'wearing a black wool cape with an asymmetric wrap front and exposed stitching',
      'wearing a Maison Margiela painted canvas jacket in white with black brushstroke details',
      'wearing an oversized black knit sweater with intentional laddering and dropped shoulders',
      'wearing a military surplus coat in black, customized with safety pins and hand-painted slogans',
      'wearing a double-layered black shirt with the outer layer slashed to reveal white underneath',
      'wearing a black neoprene bomber jacket with matte hardware and no visible branding',
      'wearing a distressed black denim chore jacket with patches of different black fabrics sewn on',
      'wearing a black silk kimono-style jacket with a wide belt, worn open over a dark tee',
      'wearing a structured black harness over a loose-fit black button-up shirt with rolled cuffs',
    ],
  },
  {
    name: 'mid_male_edge',
    category: 'wardrobe-edge',
    description: 'Male alternative fashion, waist up — dark avant-garde with trouser waistline',
    entries: [
      'wearing a studded leather jacket over a band tee, black skinny jeans with a bullet belt at the waist',
      'wearing a Rick Owens draped hoodie, drop-crotch pants visible at the waistline in matte black',
      'wearing a deconstructed denim jacket over mesh, black waxed jeans at the waist with a silver chain',
      'wearing a Yohji Yamamoto draped shirt, high-waisted wide-leg black wool trousers with a cloth belt',
      'wearing a black moto jacket over a distressed tee, black leather pants at the waist',
      'wearing a Comme des Garcons patchwork blazer, cropped black trousers at the ankle visible at the waist',
      'wearing a paint-splattered denim vest over a shredded tank, black cargo pants at the hips',
      'wearing a harness vest over a mesh top, high-waisted black bondage pants with straps at the waist',
      'wearing a bleach-splattered hoodie with raw-cut hem, distressed black jeans at the waist',
      'wearing a black linen wrap shirt, black pleated hakama-style trousers at the waist',
      'wearing a spike-studded military jacket, black skinny pants with zippers at the knee visible at the waist',
      'wearing an oversized black knit with holes, dark drop-crotch joggers at the hips',
      'wearing a distressed black blazer with safety pins, waxed black denim at the waist',
      'wearing a black leather vest over a turtleneck, belted high-waisted wide trousers',
      'wearing a gothic print silk shirt tucked into black leather pants with a matte silver belt buckle',
    ],
  },
  {
    name: 'mid_female_edge',
    category: 'wardrobe-edge',
    description: 'Female alternative fashion, waist up — dark and deconstructed with waistline',
    entries: [
      'wearing a cropped leather moto jacket over mesh, a high-waisted black leather skirt at the waist',
      'wearing a Rick Owens draped leather top, high-waisted black jersey leggings at the hips',
      'wearing a tartan corset top, a pleated black mini skirt waistband visible',
      'wearing a sheer lace blouse over a bandeau, high-waisted black wide-leg pants at the waist',
      'wearing a structured leather jacket with sharp shoulders, black skinny jeans at the waist',
      'wearing a deconstructed white shirt with frayed edges, black waxed pants at the hips',
      'wearing a cropped PVC jacket over a band tee, a black vinyl skirt at the waist',
      'wearing a draped black blazer with no closure, high-waisted black trousers with a cloth belt',
      'wearing a velvet collar top with sheer sleeves, black leather shorts at the waist',
      'wearing a corset bustier in black leather, black cargo pants with straps at the hips',
      'wearing a safety-pin denim jacket over fishnet, a black pleated skirt at the waist',
      'wearing a black silk slip top under a distressed cardigan, waxed black skinny jeans at the waist',
      'wearing a latex crop top under a plaid flannel, black biker shorts at the hips',
      'wearing a deconstructed one-lapel blazer over sheer turtleneck, black wide trousers at the waist',
      'wearing a cut-off sleeve band hoodie, a belted black leather skirt at the waist',
    ],
  },
  {
    name: 'mid_unisex_edge',
    category: 'wardrobe-edge',
    description: 'Unisex alternative fashion, waist up — dark androgynous with waistline',
    entries: [
      'wearing a Rick Owens asymmetric leather jacket, drop-crotch pants in matte black at the hips',
      'wearing a Comme des Garcons patchwork shirt, black pleated trousers at the waist',
      'wearing a bleach-drip hoodie with raw neckline, black cargo pants at the hips',
      'wearing a Yohji Yamamoto linen shirt, high-waisted hakama-style pants with a wide cloth belt',
      'wearing a deconstructed trench with exposed lining, dark wide-leg pants at the waist',
      'wearing a mesh shirt under a distressed leather vest, black bondage pants with straps at the hips',
      'wearing a black wool cape, slim black trousers visible at the waist',
      'wearing a Margiela painted jacket, black wide-leg trousers at the hips',
      'wearing a laddered knit sweater, waxed black jeans at the waist',
      'wearing a military coat with safety pins, black fatigue pants at the hips',
      'wearing a double-layered slashed shirt, black pleated trousers at the waist',
      'wearing a neoprene bomber jacket, tapered black pants at the waistline',
      'wearing a patched denim chore jacket, black carpenter pants at the hips',
      'wearing a silk kimono jacket with a wide belt, dark draped trousers at the waist',
      'wearing a structured harness over a black shirt, high-waisted wide trousers at the hips',
    ],
  },
  {
    name: 'full_male_edge',
    category: 'wardrobe-edge',
    description: 'Male alternative fashion, head to toe — complete dark outfits with shoes',
    entries: [
      'wearing a studded black leather moto jacket over a band tee, ripped black skinny jeans, and black Dr. Martens 1460 boots',
      'wearing a Rick Owens draped hoodie, drop-crotch pants in matte black, and Rick Owens Ramones high-tops',
      'wearing a deconstructed denim jacket over mesh, waxed black jeans, and pointed black leather boots',
      'wearing a Yohji Yamamoto draped shirt, wide-leg black trousers, and black Yohji platform boots',
      'wearing a Comme des Garcons patchwork blazer, cropped black trousers, and black leather creepers',
      'wearing a paint-splattered denim vest over a shredded tank, black cargos, and combat boots in matte black',
      'wearing a harness vest over mesh, black bondage pants, and tall black lace-up boots with buckles',
      'wearing a bleach-splattered hoodie, distressed black jeans, and black Converse high-tops with marker drawings',
      'wearing a black linen wrap shirt, hakama-style trousers, and black leather tabi boots',
      'wearing a spike-studded military jacket, black skinny jeans with knee zippers, and black engineer boots',
      'wearing a gothic silk shirt, black leather pants, and black western boots with silver toe tips',
      'wearing an oversized black knit with holes, drop-crotch joggers, and chunky black platform sneakers',
      'wearing a distressed blazer with safety pins, waxed denim, and black side-zip ankle boots',
      'wearing a black military coat with painted slogans, dark fatigues, and black paratrooper boots',
      'wearing a neoprene bomber, tapered black pants, and matte black Chelsea boots with a chunky sole',
    ],
  },
  {
    name: 'full_female_edge',
    category: 'wardrobe-edge',
    description: 'Female alternative fashion, head to toe — complete dark outfits with shoes',
    entries: [
      'wearing a cropped leather moto jacket over mesh, a black leather mini skirt, and tall Dr. Martens Jadon platform boots',
      'wearing a Rick Owens draped leather top, black jersey leggings, and Rick Owens wedge boots in black',
      'wearing a tartan corset top, a pleated black mini skirt, and black platform Mary Janes with chunky soles',
      'wearing a sheer lace blouse over a bandeau, wide-leg black pants, and pointed black stiletto ankle boots',
      'wearing a structured leather jacket, black skinny jeans, and black lace-up combat boots with silver eyelets',
      'wearing a deconstructed white shirt, black waxed pants, and black Vivienne Westwood Rocking Horse shoes',
      'wearing a cropped PVC jacket over a band tee, a vinyl skirt, and knee-high black patent boots',
      'wearing a draped black blazer, black trousers, and black platform sneakers with thick rubber soles',
      'wearing a velvet collar top, black leather shorts, and thigh-high black suede boots with a low heel',
      'wearing a corset bustier, black cargo pants with straps, and chunky black lug-sole boots',
      'wearing a safety-pin denim jacket over fishnet, a pleated skirt, and black Doc Marten Chelsea boots',
      'wearing a slip top under a distressed cardigan, waxed skinny jeans, and black pointed ankle boots',
      'wearing a latex crop under a plaid flannel, biker shorts, and platform Converse high-tops in black',
      'wearing a one-lapel blazer over sheer turtleneck, wide trousers, and black leather loafer platforms',
      'wearing a cut-off band hoodie, a belted leather skirt, and black creeper shoes with thick soles',
    ],
  },
  {
    name: 'full_unisex_edge',
    category: 'wardrobe-edge',
    description: 'Unisex alternative fashion, head to toe — gender-neutral dark outfits',
    entries: [
      'wearing a Rick Owens asymmetric leather jacket, drop-crotch pants, and Ramones high-top sneakers in black',
      'wearing a Comme des Garcons patchwork shirt, pleated trousers, and black leather Derby shoes with thick soles',
      'wearing a bleach-drip hoodie, black cargo pants, and Dr. Martens 1460 boots in matte black',
      'wearing a Yohji Yamamoto linen shirt, hakama pants, and black canvas high-top sneakers',
      'wearing a deconstructed trench coat, wide-leg pants, and black lug-sole Chelsea boots',
      'wearing a distressed leather vest over mesh, bondage pants, and tall black lace-up boots',
      'wearing a black wool cape, slim trousers, and pointed black leather ankle boots',
      'wearing a Margiela painted jacket, wide-leg trousers, and white Maison Margiela Replica sneakers',
      'wearing a laddered knit sweater, waxed jeans, and black suede creepers with thick rubber soles',
      'wearing a military coat with safety pins, fatigue pants, and black combat boots with silver buckles',
      'wearing a slashed double-layer shirt, pleated trousers, and black platform derbies',
      'wearing a neoprene bomber, tapered pants, and chunky black sneakers with an exaggerated sole',
      'wearing a patched denim chore jacket, carpenter pants, and black Blundstone boots',
      'wearing a silk kimono jacket, dark draped trousers, and black leather slip-on mules',
      'wearing a harness over a black shirt, wide trousers, and black Tabi boots with split toe',
    ],
  },
]

// =============================================================================
// SPORT — athletic/athleisure
// =============================================================================

const SPORT_WILDCARDS: WardrobeWildcard[] = [
  {
    name: 'close_male_sport',
    category: 'wardrobe-sport',
    description: 'Male athletic fashion, chest up — jerseys, track jackets, performance tops',
    entries: [
      'wearing a Nike Dri-FIT training hoodie in black with a reflective swoosh at the chest',
      'wearing a vintage Chicago Bulls red jersey over a black long-sleeve compression shirt',
      'wearing an Adidas Tiro track jacket in black with white triple stripes on the sleeves',
      'wearing a Jordan brand warm-up jacket in university blue with an embroidered Jumpman logo',
      'wearing a Under Armour cold gear compression mock-neck in dark gray',
      'wearing a Puma T7 track jacket in navy with gold side stripes, zipped to the chest',
      'wearing a Nike windrunner jacket in black and white color-block with a packable hood',
      'wearing a Reebok classic track jacket in red with a white vector logo on the chest',
      'wearing a vintage Lakers purple and gold warm-up jacket with snap buttons',
      'wearing an Adidas Originals Firebird track jacket in forest green with white stripes',
      'wearing a Champion mesh jersey tank in heather gray over a white long-sleeve tee',
      'wearing a New Balance athletics half-zip pullover in navy with a reflective logo',
      'wearing a Nike tech pack woven jacket in olive with zip pockets and taped seams',
      'wearing a Jordan flight suit jacket in cement gray with a tonal Jumpman on the chest',
      'wearing a vintage Starter jacket in black satin with team logo embroidery on the back',
    ],
  },
  {
    name: 'close_female_sport',
    category: 'wardrobe-sport',
    description: 'Female athletic fashion, chest up — sports bras, crop tanks, track jackets',
    entries: [
      'wearing a Nike Dri-FIT cropped hoodie in pale pink with a white swoosh at the chest',
      'wearing a fitted Adidas three-stripe sports bra in black with a matching zip-up track jacket unzipped',
      'wearing a Lululemon Define jacket in dark olive with a fitted silhouette and thumbhole cuffs',
      'wearing a Jordan brand crop tee in university blue with a metallic Jumpman logo',
      'wearing a Puma crop tank top in coral with the Puma cat logo at the center',
      'wearing a Under Armour HeatGear compression top in black with a mesh back panel',
      'wearing a Nike windrunner jacket in lavender and white color-block, zipped halfway',
      'wearing a Reebok cropped track jacket in red with white vector stripe on the sleeve',
      'wearing a vintage-style Lakers crop jersey in purple over a black sports bra',
      'wearing an Adidas Originals crop hoodie in cloud white with trefoil logo',
      'wearing a New Balance fitted crop top in navy with reflective piping',
      'wearing a Champion reverse-weave crop sweatshirt in Oxford gray',
      'wearing a Nike Sportswear Essential crop tee in sage green, relaxed fit',
      'wearing a fitted Gymshark seamless crop tank in deep teal with a high neckline',
      'wearing a Fila cropped track jacket in white with navy and red accent stripes',
    ],
  },
  {
    name: 'close_unisex_sport',
    category: 'wardrobe-sport',
    description: 'Unisex athletic fashion, chest up — oversized jerseys, track tops, athletic layers',
    entries: [
      'wearing an oversized Nike Dri-FIT training hoodie in dark gray with a reflective swoosh',
      'wearing a vintage oversized basketball jersey in white over a long-sleeve black compression shirt',
      'wearing an Adidas Originals Beckenbauer track jacket in navy with gold stripes',
      'wearing a Nike ACG fleece pullover in black and green with a quarter-zip collar',
      'wearing a Puma T7 track jacket in forest green with cream side stripes',
      'wearing a Champion reverse-weave hoodie in purple with a small C logo embroidery',
      'wearing an oversized mesh practice jersey in heather gray over a white long-sleeve base layer',
      'wearing a New Balance athletics windbreaker in black and orange, packed hood at the collar',
      'wearing a Nike tech fleece crewneck in dark heather with bonded seams',
      'wearing an Adidas Tiro warm-up top in black with subtle tonal stripes',
      'wearing a Jordan warm-up pullover in cool gray with a kangaroo pocket',
      'wearing a Under Armour storm jacket in charcoal with water-resistant coating',
      'wearing a Reebok classic nylon jacket in navy with a foldable hood',
      'wearing a vintage sports warm-up jacket in red satin with white snap buttons',
      'wearing a Nike running vest in matte black over a long-sleeve base layer in dark gray',
    ],
  },
  {
    name: 'mid_male_sport',
    category: 'wardrobe-sport',
    description: 'Male athletic fashion, waist up — track suits, jerseys with pants waistline',
    entries: [
      'wearing a Nike Dri-FIT hoodie in black, matching joggers visible at the drawstring waist',
      'wearing a vintage Bulls jersey over a compression shirt, black basketball shorts at the waist',
      'wearing an Adidas Tiro track jacket in black, matching track pants with white stripes at the hips',
      'wearing a Jordan warm-up jacket in blue, matching basketball shorts at the waist',
      'wearing a Under Armour compression mock-neck, gray athletic shorts with the UA logo at the waist',
      'wearing a Puma track jacket in navy, matching T7 track pants visible at the waistline',
      'wearing a Nike windrunner jacket, black running tights visible at the waist',
      'wearing a vintage Starter jacket, baggy mesh basketball shorts at the hips',
      'wearing an Adidas Firebird track jacket in green, white-striped track pants at the waist',
      'wearing a Champion mesh jersey, gray Champion cotton shorts with a drawstring waist',
      'wearing a New Balance half-zip pullover, dark running pants with reflective strips at the waist',
      'wearing a Nike tech pack jacket in olive, matching woven cargo joggers at the hips',
      'wearing a Jordan flight suit jacket, matching cement gray joggers at the waist',
      'wearing a Reebok track jacket in red, matching track pants at the waistline',
      'wearing a running vest over a long-sleeve base layer, fitted running tights at the waist',
    ],
  },
  {
    name: 'mid_female_sport',
    category: 'wardrobe-sport',
    description: 'Female athletic fashion, waist up — crop tops, track jackets with leggings/shorts waistline',
    entries: [
      'wearing a Nike cropped hoodie in pink, high-waisted black leggings at the waist',
      'wearing a fitted Adidas sports bra under a track jacket, matching track pants at the hips',
      'wearing a Lululemon Define jacket in olive, high-waisted Align leggings visible at the waist',
      'wearing a Jordan crop tee in blue, high-waisted biker shorts in black at the waist',
      'wearing a Puma crop tank in coral, matching high-waisted leggings at the hips',
      'wearing a Under Armour HeatGear top, dark running shorts with the UA logo at the waist',
      'wearing a Nike windrunner in lavender, matching running leggings at the waistline',
      'wearing a Reebok crop track jacket, matching high-waisted track pants at the waist',
      'wearing a vintage crop jersey in purple, high-waisted black biker shorts at the hips',
      'wearing an Adidas crop hoodie in white, matching track pants at the waistline',
      'wearing a New Balance crop top in navy, dark running leggings at the waist',
      'wearing a Champion crop sweatshirt in gray, matching cotton shorts at the hips',
      'wearing a Nike Essential crop tee in sage, high-waisted black joggers at the waist',
      'wearing a Gymshark crop tank in teal, matching seamless leggings at the hips',
      'wearing a Fila crop track jacket in white, matching track pants with accent stripes at the waist',
    ],
  },
  {
    name: 'mid_unisex_sport',
    category: 'wardrobe-sport',
    description: 'Unisex athletic fashion, waist up — oversized athletic layers with waistline',
    entries: [
      'wearing an oversized Nike training hoodie in gray, matching joggers at the drawstring waist',
      'wearing a vintage oversized basketball jersey, baggy mesh shorts at the waist',
      'wearing an Adidas Beckenbauer jacket in navy, matching track pants at the hips',
      'wearing a Nike ACG fleece pullover, black nylon cargo pants at the waistline',
      'wearing a Puma track jacket in green, matching track pants at the waist',
      'wearing a Champion hoodie in purple, matching sweatpants at the hips',
      'wearing a mesh practice jersey over a base layer, athletic shorts at the waist',
      'wearing a New Balance windbreaker in black, dark joggers at the waistline',
      'wearing a Nike tech fleece crewneck, matching tech fleece joggers at the waist',
      'wearing an Adidas Tiro warm-up top, matching slim track pants at the hips',
      'wearing a Jordan warm-up pullover in gray, matching joggers at the drawstring waist',
      'wearing a Under Armour storm jacket, dark running tights at the waistline',
      'wearing a Reebok nylon jacket in navy, matching nylon pants at the waist',
      'wearing a vintage warm-up jacket in red, matching track pants at the hips',
      'wearing a Nike running vest over a base layer, dark running pants at the waist',
    ],
  },
  {
    name: 'full_male_sport',
    category: 'wardrobe-sport',
    description: 'Male athletic fashion, head to toe — complete athletic outfits with sneakers',
    entries: [
      'wearing a Nike Dri-FIT black tracksuit with zip hoodie and slim joggers, white Air Force 1 Lows',
      'wearing a vintage Bulls jersey over a compression shirt, black basketball shorts, and Air Jordan 1 Retro Highs in Chicago colorway',
      'wearing an Adidas Tiro track jacket and pants in black with white stripes, and Adidas Ultraboost in core black',
      'wearing a Jordan warm-up suit in university blue, and Jordan 4 Retros in military blue',
      'wearing a Puma T7 track jacket and pants in navy with gold stripes, and Puma Suede Classics in black',
      'wearing a Nike windrunner in black and white, matching joggers, and Nike Air Max 90s in infrared',
      'wearing a vintage Starter jacket in black satin, baggy mesh shorts, and classic white Nike Cortez',
      'wearing an Adidas Firebird track suit in green with white stripes, and Adidas Samba OGs in white',
      'wearing a Champion mesh jersey and cotton shorts in gray, and New Balance 990v5s in gray',
      'wearing a Nike tech pack woven jacket and cargo joggers in olive, and Nike ISPA sneakers in dark gray',
      'wearing a Under Armour compression mock and athletic shorts in gray, and UA HOVR Phantom running shoes',
      'wearing a Reebok classic track suit in red with white vector logo, and Reebok Club C 85s in white',
      'wearing a New Balance athletics half-zip and running pants in navy, and New Balance 2002R in cream',
      'wearing a Jordan flight suit in cement gray, and Jordan 11 Retros in Concord',
      'wearing a Nike running vest over a base layer, running tights, and Nike Vaporfly Next% in neon green',
    ],
  },
  {
    name: 'full_female_sport',
    category: 'wardrobe-sport',
    description: 'Female athletic fashion, head to toe — complete athletic outfits with sneakers',
    entries: [
      'wearing a Nike cropped hoodie in pink, high-waisted black leggings, and Nike Dunk Lows in rose whisper',
      'wearing a fitted Adidas track jacket and matching pants in black, and Adidas Ultraboost in cloud white',
      'wearing a Lululemon Define jacket in olive, Align leggings, and New Balance 327s in sea salt',
      'wearing a Jordan crop tee in blue, black biker shorts, and Jordan 1 Lows in mocha',
      'wearing a Puma crop tank and matching leggings in coral, and Puma Speedcat OGs in red',
      'wearing a Nike windrunner in lavender, matching leggings, and Nike Air Max 97s in barely rose',
      'wearing a Reebok crop track suit in red with white accents, and Reebok Classic Leather in white',
      'wearing a vintage crop jersey in purple, black biker shorts, and Converse Run Star Hike platforms in white',
      'wearing an Adidas crop hoodie in white, matching track pants, and Adidas Gazelle Bold in pink',
      'wearing a Champion crop sweatshirt and shorts in gray, and Nike Air Max Plus in triple white',
      'wearing a New Balance crop top in navy, dark running leggings, and New Balance Fresh Foam in gray',
      'wearing a Nike Essential crop tee in sage, black joggers, and Nike Blazer Mid 77s in white',
      'wearing a Gymshark crop tank and seamless leggings in teal, and Nike Free Metcon 5 in dark gray',
      'wearing a Fila crop track jacket in white, matching pants, and Fila Disruptor 2s in white',
      'wearing a Under Armour sports bra and HeatGear leggings in black, and UA HOVR Phantom in white',
    ],
  },
  {
    name: 'full_unisex_sport',
    category: 'wardrobe-sport',
    description: 'Unisex athletic fashion, head to toe — gender-neutral athletic outfits with sneakers',
    entries: [
      'wearing an oversized Nike training hoodie and matching joggers in gray, and Nike Air Force 1 Lows in white',
      'wearing a vintage basketball jersey over a compression shirt, baggy mesh shorts, and Converse All Star Highs in white',
      'wearing an Adidas Beckenbauer track suit in navy with gold stripes, and Adidas Samba OGs in white',
      'wearing a Nike ACG fleece pullover, black nylon cargo pants, and Nike ACG Mountain Fly boots',
      'wearing a Puma track suit in forest green with cream stripes, and Puma Clyde All-Pro in white',
      'wearing a Champion hoodie and matching sweatpants in purple, and New Balance 550s in white and purple',
      'wearing a mesh practice jersey over a base layer, athletic shorts, and Nike Vomero 5 in platinum',
      'wearing a New Balance windbreaker and joggers in black, and New Balance 2002R in black and gray',
      'wearing a Nike tech fleece crewneck and matching joggers in heather, and Air Max 90s in triple black',
      'wearing an Adidas Tiro warm-up suit in black with tonal stripes, and Adidas Ultraboost in core black',
      'wearing a Jordan warm-up pullover and joggers in cool gray, and Jordan 1 Mid in cool gray',
      'wearing a Under Armour storm jacket and running tights in charcoal, and UA HOVR Sonic in gray',
      'wearing a Reebok nylon jacket and matching pants in navy, and Reebok Nano X3 in black',
      'wearing a vintage warm-up suit in red satin, and Nike Cortez in white and red',
      'wearing a Nike running vest, base layer, running tights, and Nike Pegasus 40 in black and white',
    ],
  },
]

// =============================================================================
// CASUAL — everyday/relaxed
// =============================================================================

const CASUAL_WILDCARDS: WardrobeWildcard[] = [
  {
    name: 'close_male_casual',
    category: 'wardrobe-casual',
    description: 'Male casual fashion, chest up — relaxed everyday tops and layers',
    entries: [
      'wearing a washed navy crew-neck tee with a relaxed fit and rolled sleeves',
      'wearing an unbuttoned light blue oxford shirt over a plain white crewneck tee',
      'wearing a Patagonia Better Sweater fleece quarter-zip in dark gray',
      'wearing a faded olive green henley with three-button placket and pushed-up sleeves',
      'wearing a navy and white Breton-stripe long-sleeve tee with a boat neck',
      'wearing a Levi\'s denim trucker jacket in medium wash over a black pocket tee',
      'wearing a simple gray marl crewneck sweatshirt with a relaxed dropped shoulder',
      'wearing a cream cable-knit fisherman sweater with a crew neck',
      'wearing a dark green Barbour quilted jacket with a corduroy collar',
      'wearing a charcoal merino wool v-neck sweater over a white button-down collar',
      'wearing a washed black pocket tee under an open chambray shirt in light blue',
      'wearing a heather gray zip-up hoodie with a white drawstring, open over a navy tee',
      'wearing a tan linen camp-collar shirt with short sleeves and a relaxed drape',
      'wearing a burgundy rugby polo with a white collar and a rubber button placket',
      'wearing a heavyweight oatmeal waffle-knit thermal henley with wood buttons',
    ],
  },
  {
    name: 'close_female_casual',
    category: 'wardrobe-casual',
    description: 'Female casual fashion, chest up — relaxed everyday tops and layers',
    entries: [
      'wearing a fitted white crewneck tee with a slightly cropped hem',
      'wearing an oversized light blue chambray shirt, sleeves rolled to the elbows',
      'wearing a soft oatmeal cashmere crew-neck sweater with a relaxed fit',
      'wearing a striped Breton tee in navy and white with a boat neckline',
      'wearing a sage green linen button-up blouse with the top button open',
      'wearing a Patagonia fleece pullover in dusty rose with a snap-T chest pocket',
      'wearing a vintage-wash gray sweatshirt with a wide crew neck slipping off one shoulder',
      'wearing a fitted white tank top under a light denim jacket, sleeves pushed up',
      'wearing a cream waffle-knit henley with wood buttons and thumb-hole cuffs',
      'wearing a relaxed-fit black v-neck tee with a small chest pocket',
      'wearing a dusty blue cotton popover blouse with a half-button placket',
      'wearing a camel-colored cardigan in fine knit, buttoned halfway over a white tee',
      'wearing a ribbed mock-neck top in off-white, fitted and minimal',
      'wearing a vintage-style ringer tee in white with red contrast trim at the neck and sleeves',
      'wearing a soft gray hoodie with a front pouch pocket, drawstrings hanging loose',
    ],
  },
  {
    name: 'close_unisex_casual',
    category: 'wardrobe-casual',
    description: 'Unisex casual fashion, chest up — relaxed, gender-neutral everyday tops',
    entries: [
      'wearing an oversized washed black crewneck tee with a boxy fit',
      'wearing a light blue chambray shirt, buttoned halfway with sleeves rolled up',
      'wearing a heavyweight cream sweatshirt with a relaxed drop-shoulder fit',
      'wearing a navy and white Breton-stripe long-sleeve tee in a relaxed cut',
      'wearing a dark olive henley with three-button placket and pushed-up sleeves',
      'wearing a Patagonia Synchilla fleece pullover in natural oatmeal',
      'wearing a faded vintage band tee in washed gray under an open flannel in blue and brown',
      'wearing a cream cable-knit sweater with a relaxed crew neck',
      'wearing a simple gray zip-up hoodie, open over a plain white tee',
      'wearing a denim trucker jacket in medium wash over a plain black tee',
      'wearing a tan linen camp-collar shirt with a relaxed boxy drape',
      'wearing a charcoal merino crewneck sweater, simple and clean',
      'wearing a washed olive pocket tee under an unbuttoned plaid flannel in red and black',
      'wearing a heavyweight waffle-knit thermal in oatmeal with a crew neck',
      'wearing a quilted vest in navy over a gray crewneck sweatshirt',
    ],
  },
  {
    name: 'mid_male_casual',
    category: 'wardrobe-casual',
    description: 'Male casual fashion, waist up — relaxed tops with pant waistlines',
    entries: [
      'wearing a navy crewneck tee, faded indigo straight-leg jeans at the waist with a brown leather belt',
      'wearing a light blue oxford shirt tucked into khaki chinos with a woven brown belt',
      'wearing a Patagonia fleece quarter-zip, dark olive chinos at the waist',
      'wearing an olive henley with pushed-up sleeves, dark wash jeans at the waist',
      'wearing a Breton-stripe tee, tan chinos at the waist with a canvas belt',
      'wearing a denim trucker jacket over a tee, dark straight-leg jeans at the waist',
      'wearing a gray crewneck sweatshirt, light wash relaxed jeans at the hips',
      'wearing a cream fisherman sweater, dark corduroy pants at the waist',
      'wearing a Barbour quilted jacket, dark jeans with a brown belt at the waist',
      'wearing a charcoal v-neck sweater over a white shirt, gray chinos at the waist',
      'wearing a chambray shirt over a tee, olive chinos at the waist with a leather belt',
      'wearing a heather gray zip hoodie over a navy tee, dark joggers at the waist',
      'wearing a tan linen camp-collar shirt, cream linen pants at the waist',
      'wearing a burgundy rugby polo, khaki straight-leg pants at the waist',
      'wearing an oatmeal thermal henley, brown carpenter pants at the waist',
    ],
  },
  {
    name: 'mid_female_casual',
    category: 'wardrobe-casual',
    description: 'Female casual fashion, waist up — relaxed tops with skirt/pant waistlines',
    entries: [
      'wearing a fitted white crewneck tee, high-waisted light wash mom jeans at the waist',
      'wearing a chambray shirt knotted at the waist, dark straight-leg jeans at the hips',
      'wearing a cashmere crewneck in oatmeal, a tan midi skirt waistband visible',
      'wearing a striped Breton tee, high-waisted navy wide-leg trousers at the waist',
      'wearing a sage linen blouse tucked into high-waisted cream linen shorts',
      'wearing a Patagonia fleece pullover in rose, dark leggings at the waist',
      'wearing a vintage gray sweatshirt, high-waisted straight-leg jeans at the waist',
      'wearing a fitted tank under a denim jacket, a floral midi skirt waistband visible',
      'wearing a waffle henley in cream, high-waisted olive cargo pants at the waist',
      'wearing a black v-neck tee, medium-wash relaxed jeans at the hips',
      'wearing a blue cotton popover blouse, white wide-leg pants at the waist',
      'wearing a camel cardigan over a white tee, dark skinny jeans at the waist',
      'wearing a ribbed mock-neck in off-white, high-waisted black trousers at the waist',
      'wearing a ringer tee in white with red trim, blue denim shorts at the waist',
      'wearing a soft gray hoodie, black leggings at the waist',
    ],
  },
  {
    name: 'mid_unisex_casual',
    category: 'wardrobe-casual',
    description: 'Unisex casual fashion, waist up — relaxed, gender-neutral with waistline',
    entries: [
      'wearing an oversized black crewneck tee, relaxed dark jeans at the waist',
      'wearing a chambray shirt buttoned halfway, tan chinos at the waist with a canvas belt',
      'wearing a cream sweatshirt with drop shoulders, olive wide-leg pants at the hips',
      'wearing a Breton-stripe tee, dark straight-leg jeans at the waist',
      'wearing an olive henley, brown carpenter pants at the waist',
      'wearing a Patagonia fleece pullover, dark joggers at the waistline',
      'wearing a band tee under a flannel, relaxed jeans at the hips',
      'wearing a cable-knit sweater in cream, corduroy pants at the waist',
      'wearing a gray zip hoodie over a white tee, dark sweatpants at the waist',
      'wearing a denim trucker jacket over a tee, khaki chinos at the waist',
      'wearing a linen camp-collar shirt, cream linen pants at the waist',
      'wearing a charcoal merino crewneck, dark chinos at the hips',
      'wearing an olive pocket tee under a plaid flannel, relaxed jeans at the waist',
      'wearing a waffle thermal in oatmeal, dark cargo pants at the hips',
      'wearing a quilted vest over a sweatshirt, dark straight-leg jeans at the waist',
    ],
  },
  {
    name: 'full_male_casual',
    category: 'wardrobe-casual',
    description: 'Male casual fashion, head to toe — complete everyday outfits with shoes',
    entries: [
      'wearing a navy crewneck tee, faded indigo straight-leg jeans, and white Converse Chuck 70 Lows',
      'wearing a light blue oxford shirt, khaki chinos, and brown leather desert boots',
      'wearing a Patagonia fleece quarter-zip, olive chinos, and tan suede Clarks Wallabees',
      'wearing an olive henley, dark wash jeans, and brown Red Wing Iron Ranger boots',
      'wearing a Breton-stripe tee, tan chinos, and white canvas sneakers',
      'wearing a denim trucker jacket over a tee, dark jeans, and white Vans Authentic',
      'wearing a gray crewneck sweatshirt, relaxed light wash jeans, and New Balance 574s in gray',
      'wearing a cream fisherman sweater, dark corduroy pants, and brown leather Chelsea boots',
      'wearing a Barbour quilted jacket, dark jeans, and brown leather lace-up boots',
      'wearing a charcoal v-neck sweater over a white shirt, gray chinos, and white minimalist leather sneakers',
      'wearing a chambray shirt over a tee, olive chinos, and Birkenstock Arizona sandals in brown',
      'wearing a heather gray zip hoodie, dark joggers, and Nike Killshot 2s in sail and gum',
      'wearing a tan linen camp-collar shirt, cream linen pants, and tan leather espadrilles',
      'wearing a burgundy rugby polo, khaki pants, and classic white Stan Smith sneakers',
      'wearing an oatmeal thermal henley, brown carpenter pants, and Blundstone boots in brown',
    ],
  },
  {
    name: 'full_female_casual',
    category: 'wardrobe-casual',
    description: 'Female casual fashion, head to toe — complete everyday outfits with shoes',
    entries: [
      'wearing a fitted white crewneck tee, high-waisted mom jeans, and white Adidas Gazelle sneakers',
      'wearing a chambray shirt knotted at the waist, dark jeans, and tan leather mules',
      'wearing a cashmere crewneck in oatmeal, a tan midi skirt, and cream ballet flats',
      'wearing a striped Breton tee, navy wide-leg trousers, and white canvas sneakers',
      'wearing a sage linen blouse, cream linen shorts, and brown leather sandals',
      'wearing a Patagonia fleece in rose, dark leggings, and New Balance 327s in sea salt',
      'wearing a vintage gray sweatshirt, straight-leg jeans, and Converse Chuck 70 Highs in cream',
      'wearing a fitted tank under a denim jacket, a floral midi skirt, and white leather sneakers',
      'wearing a waffle henley in cream, olive cargo pants, and Birkenstock Boston clogs in taupe',
      'wearing a black v-neck tee, relaxed medium wash jeans, and black leather ankle boots',
      'wearing a blue cotton popover blouse, white wide-leg pants, and woven leather sandals in tan',
      'wearing a camel cardigan over a white tee, dark skinny jeans, and pointed-toe tan suede flats',
      'wearing a ribbed mock-neck in off-white, black trousers, and black loafers with a low heel',
      'wearing a ringer tee in white, blue denim shorts, and classic white Converse low-tops',
      'wearing a soft gray hoodie, black leggings, and Nike Daybreak sneakers in pale pink',
    ],
  },
  {
    name: 'full_unisex_casual',
    category: 'wardrobe-casual',
    description: 'Unisex casual fashion, head to toe — gender-neutral everyday outfits with shoes',
    entries: [
      'wearing an oversized black crewneck tee, relaxed dark jeans, and white Converse Chuck 70 Lows',
      'wearing a chambray shirt, tan chinos, and brown suede desert boots',
      'wearing a cream sweatshirt, olive wide-leg pants, and New Balance 990v5s in gray',
      'wearing a Breton-stripe tee, dark straight-leg jeans, and white canvas Vans Authentic',
      'wearing an olive henley, brown carpenter pants, and tan leather work boots',
      'wearing a Patagonia fleece pullover, dark joggers, and Birkenstock Bostons in taupe suede',
      'wearing a band tee under a flannel, relaxed jeans, and Converse Chuck Taylor Highs in black',
      'wearing a cable-knit sweater, corduroy pants, and brown leather Chelsea boots',
      'wearing a gray zip hoodie over a white tee, dark sweatpants, and Nike Killshot 2s in sail',
      'wearing a denim trucker jacket over a tee, khaki chinos, and white Adidas Stan Smiths',
      'wearing a linen camp-collar shirt, cream linen pants, and tan leather slide sandals',
      'wearing a charcoal merino crewneck, dark chinos, and black minimalist leather sneakers',
      'wearing an olive pocket tee under a flannel, relaxed jeans, and red Vans Old Skool',
      'wearing a waffle thermal in oatmeal, cargo pants, and Clarks Wallabees in beeswax',
      'wearing a quilted vest over a sweatshirt, straight-leg jeans, and brown Blundstone boots',
    ],
  },
]

// =============================================================================
// EXPORT ALL
// =============================================================================

export const WARDROBE_WILDCARDS: WardrobeWildcard[] = [
  ...STREET_WILDCARDS,
  ...LUX_WILDCARDS,
  ...EDGE_WILDCARDS,
  ...SPORT_WILDCARDS,
  ...CASUAL_WILDCARDS,
]
