#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 005

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 005-complete-reference-image-persistence-to-supabase"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Start Next.js development server
echo "Starting Next.js development server..."
npm run dev &
NEXT_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:3000"
echo ""
echo "Task:"
echo "  Fix dual autocomplete dropdown bug"
echo "  Verify reference persistence to Supabase"
echo ""
echo "Key Files to Modify:"
echo "  - src/features/shot-creator/components/creator-prompt-settings/PromptActions.tsx"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

# Wait for the process
wait $NEXT_PID
