'use client'

import { ModelViewer } from '@/features/figurine-studio/components/ModelViewer'

// Test GLB generated by Trellis from a random image
const TEST_GLB_URL = 'https://replicate.delivery/yhqm/XeVIfMgIdisnB0tw2dqiuAbsh8BM7tgHPjZH3UDlZbfCUTeYB/output.glb'

export default function TestModelViewerPage() {
  return (
    <div className="h-screen w-full bg-zinc-950 text-white flex flex-col items-center justify-center p-8">
      <h1 className="text-2xl font-bold mb-4">3D Model Viewer Test</h1>
      <p className="text-sm text-zinc-400 mb-6">GLB from Trellis - drag to rotate, scroll to zoom</p>
      <div className="w-[600px] h-[600px] rounded-xl overflow-hidden border border-zinc-800 bg-black">
        <ModelViewer
          src={TEST_GLB_URL}
          alt="Test 3D figurine from Trellis"
          className="w-full h-full"
          autoRotate
          cameraControls
        />
      </div>
    </div>
  )
}
