'use client'

import { useState, useCallback } from 'react'
import { FrameExtractor } from '@/features/layout-annotation/components/frame-extractor'
import type { FrameExtractionResult } from '@/features/layout-annotation/types/frame-extractor.types'
import { createLogger } from '@/lib/logger'


const log = createLogger('App')
export default function TestFrameExtractorPage() {
  const [imageUrl, setImageUrl] = useState<string | null>(null)
  const [showExtractor, setShowExtractor] = useState(false)
  const [results, setResults] = useState<FrameExtractionResult[]>([])

  const handleFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    const url = URL.createObjectURL(file)
    setImageUrl(url)
    setShowExtractor(true)
  }, [])

  const handleClose = useCallback(() => {
    if (imageUrl) {
      URL.revokeObjectURL(imageUrl)
    }
    setImageUrl(null)
    setShowExtractor(false)
  }, [imageUrl])

  const handleExtract = useCallback((frames: FrameExtractionResult[]) => {
    log.info('Extracted frames', { frames: frames })
    setResults(frames)

    // Download each frame
    if (frames.length > 0 && frames[0].dataUrl) {
      frames.forEach((frame, index) => {
        const link = document.createElement('a')
        link.href = frame.dataUrl
        link.download = `frame_${index + 1}_r${frame.row + 1}_c${frame.col + 1}.png`
        link.click()
      })
    }

    handleClose()
  }, [handleClose])

  return (
    <div className="min-h-screen bg-background text-white p-8">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-3xl font-bold mb-2">Frame Extractor Test</h1>
        <p className="text-muted-foreground mb-8">
          Standalone test page for the Frame Extractor feature. No authentication required.
        </p>

        {/* Upload Section */}
        <div className="bg-card rounded-lg p-6 mb-8">
          <h2 className="text-xl font-semibold mb-4">1. Select a Composite Image</h2>
          <p className="text-muted-foreground mb-4">
            Upload a 3×3 grid composite image (like those generated by Nano Banana)
          </p>

          <label className="block">
            <input
              type="file"
              accept="image/*"
              onChange={handleFileSelect}
              className="block w-full text-sm text-muted-foreground
                file:mr-4 file:py-3 file:px-6
                file:rounded-lg file:border-0
                file:text-sm file:font-semibold
                file:bg-accent file:text-white
                hover:file:bg-cyan-700
                file:cursor-pointer cursor-pointer"
            />
          </label>
        </div>

        {/* Instructions */}
        <div className="bg-card rounded-lg p-6 mb-8">
          <h2 className="text-xl font-semibold mb-4">2. How to Test</h2>
          <ul className="list-disc list-inside space-y-2 text-foreground">
            <li>After selecting an image, the Frame Extractor will open</li>
            <li>Adjust the grid using the <strong>Rows/Cols sliders</strong> (default 3×3)</li>
            <li>Use <strong>Offset X/Y</strong> to move the grid start position</li>
            <li>Use <strong>Gutter X/Y</strong> if there&apos;s spacing between frames</li>
            <li>Click individual cells to select them (highlighted in green)</li>
            <li>Choose <strong>16:9 or 9:16</strong> output aspect ratio</li>
            <li>Click <strong>&quot;Download Frames&quot;</strong> to extract and download all frames</li>
          </ul>
        </div>

        {/* Results */}
        {results.length > 0 && (
          <div className="bg-card rounded-lg p-6">
            <h2 className="text-xl font-semibold mb-4">3. Results</h2>
            <p className="text-emerald-400 mb-4">
              ✓ Successfully extracted {results.length} frames!
            </p>
            <div className="grid grid-cols-3 gap-4">
              {results.map((result, index) => (
                <div key={index} className="bg-secondary rounded p-3 text-center">
                  <div className="mb-2 overflow-hidden rounded bg-muted">
                    <img
                      src={result.dataUrl}
                      alt={`Frame ${index + 1}`}
                      className="w-full h-auto object-contain"
                    />
                  </div>
                  <div className="text-sm">
                    Frame {index + 1}
                    <br />
                    <span className="text-muted-foreground">
                      Row {result.row + 1}, Col {result.col + 1}
                    </span>
                    <br />
                    <span className="text-muted-foreground">
                      {result.width}×{result.height}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Frame Extractor Modal */}
        {showExtractor && imageUrl && (
          <FrameExtractor
            imageUrl={imageUrl}
            onClose={handleClose}
            onExtract={handleExtract}
          />
        )}
      </div>
    </div>
  )
}
