#!/bin/bash

# Auto-Build Environment Setup for User Prompts Organization System
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js Development Server..."
echo ""

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# Start Next.js dev server
npm run dev &
DEV_PID=$!

# Wait for Next.js to be ready
wait_for_service 3000 "Next.js App"

# ============================================
# APPLY DATABASE MIGRATIONS
# ============================================

echo ""
echo "Checking database migrations..."
echo ""

# Check if migration file exists
if [ -f "supabase/migrations/20251225000000_create_user_prompts_system.sql" ]; then
    echo -e "${GREEN}Migration file found${NC}"
    echo "To apply migration, run:"
    echo "  npx supabase db push"
else
    echo -e "${YELLOW}Migration file not yet created - will be created in Phase 1${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Next.js App:  http://localhost:3000"
echo "  Supabase:     https://tarohelkwuurakbxjyxm.supabase.co"
echo ""
echo "To stop services, press Ctrl+C or run:"
echo "  kill $DEV_PID"
echo ""
echo "Next steps:"
echo "  1. Ensure database migration is applied: npx supabase db push"
echo "  2. Open http://localhost:3000 in your browser"
echo "  3. Start implementing subtasks from implementation_plan.json"
echo ""
