#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 015 - Fix Mobile Layout Issues in Prompt Tools UI

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=60
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ] || [ "package.json" -nt "node_modules" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Next.js development server..."
npm run dev &
wait_for_service 3000 "Next.js Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "To test mobile layout:"
echo "  1. Open Chrome DevTools (F12)"
echo "  2. Toggle Device Toolbar (Ctrl+Shift+M)"
echo "  3. Select iPhone SE (375px) or custom viewport"
echo "  4. Navigate to Prompt Tools section"
echo ""
echo "Test viewports:"
echo "  - 375px (iPhone SE)"
echo "  - 428px (iPhone 12/13 Pro Max)"
echo "  - 768px (iPad Mini)"
echo "  - 1024px (Desktop - verify no regression)"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for any background process
wait
