/**
 * Storybook Types
 * Types for the children's book creator feature
 */

// =============================================================================
// BEATS → SPREADS → PAGES ARCHITECTURE
// =============================================================================
//
// Core Concepts:
// - BEAT: A story moment generated by AI (1 beat = 1 spread)
// - SPREAD: Two facing pages (user decides text placement)
// - PAGE: A single physical page in the book
//
// Formula: beats = pageCount / 2
// Each beat maps to exactly 1 spread (2 physical pages)
// =============================================================================

/**
 * StoryBeat - What AI generates
 * Each beat represents a single story moment that will become one spread
 */
export interface StoryBeat {
  id: string
  beatNumber: number           // 1, 2, 3... (sequential)
  text: string                 // Story text for this moment
  sceneDescription: string     // Visual description for image generation
  learningNote?: string        // Educational callout (optional)
}

/**
 * Image mode options for spreads
 * Determines how images are generated for a spread
 */
export type SpreadImageMode =
  | 'full-spread'    // One continuous 2:1 image, split into left/right
  | 'split'          // Two separate images generated independently
  | 'left-only'      // Image on left page only
  | 'right-only'     // Image on right page only
  | 'none'           // Text-only spread (no images)

/**
 * BookSpread - User layout design
 * Created in Layout Editor step, represents two facing pages
 */
export interface BookSpread {
  id: string
  spreadNumber: number         // 1, 2, 3... (sequential)

  // Content (from beat)
  beatId: string               // Links to StoryBeat
  text: string                 // Full beat text (may be split)
  sceneDescription: string     // From beat

  // Image Generation
  spreadImageUrl?: string      // Full 2:1 spread image (before split)
  leftImageUrl?: string        // Left half (after split) or standalone
  rightImageUrl?: string       // Right half (after split) or standalone
  imageMode: SpreadImageMode

  // Text Placement (USER DECIDES)
  textPlacement: SpreadTextPosition  // 'left' | 'right' | 'both' | 'none'
  leftPageText?: string        // Text for left page (if textPlacement includes left)
  rightPageText?: string       // Text for right page (if textPlacement includes right)
  textPosition: TextPosition   // 'top' | 'bottom' position on the page

  // Physical Page Mapping
  leftPageNumber: number       // e.g., 7 (even pages are left)
  rightPageNumber: number      // e.g., 8 (odd pages are right)

  // Generation State
  isGenerated: boolean
  isGenerating: boolean
}

/**
 * PhysicalPage - For PDF export
 * Derived from spreads for final rendering
 */
export interface PhysicalPage {
  pageNumber: number
  pageType: PageType

  // Content
  imageUrl?: string
  text?: string
  textPosition?: TextPosition

  // Layout
  isLeftPage: boolean          // Even numbered pages
  isRightPage: boolean         // Odd numbered pages
  spreadId?: string            // Links back to BookSpread (for story pages)

  // Metadata
  isFrontMatter?: boolean
  isBackMatter?: boolean
}

// =============================================================================
// ORIGINAL TYPES (kept for compatibility)
// =============================================================================

// Expression keywords from character sheet
export type CharacterExpression =
  | 'neutral'
  | 'happy'
  | 'angry'
  | 'speaking'
  | 'smug'
  | 'confident'
  | 'sad'
  | 'surprised'
  | 'shouting'
  | 'whispering'

// Character position in scene
export type CharacterPosition = 'left' | 'center' | 'right' | 'background'

// Camera shot types
export type CameraShot = 'wide' | 'medium' | 'close-up' | 'extreme-close-up'
export type CameraAngle = 'eye-level' | 'low-angle' | 'high-angle' | 'birds-eye'

// Text overlay position
export type TextPosition = 'top' | 'bottom' | 'left' | 'right' | 'none'

// Page type for extended book structure (Amazon KDP compliance)
// Front matter, story pages, and back matter types
export type PageType =
  | 'half-title'      // Just title, simple (page 1)
  | 'frontispiece'    // Opening illustration (page 2)
  | 'title-page'      // Full title page (page 3)
  | 'copyright'       // Legal page (page 4)
  | 'dedication'      // Personal dedication (page 5)
  | 'blank'           // Intentionally blank page
  | 'story-single'    // Single page story content
  | 'story-spread'    // Two-page spread (one image spans both)
  | 'the-end'         // Closing page
  | 'about-author'    // Author bio page
  | 'other-books'     // Series/collection page

// Spread position - where text appears on a spread
export type SpreadTextPosition = 'left' | 'right' | 'both' | 'none'

// Page type configurations for UI
export const PAGE_TYPE_CONFIG: Record<PageType, {
  name: string
  description: string
  icon: string
  category: 'front-matter' | 'story' | 'back-matter'
  defaultLayout: PageLayout
  requiresImage: boolean
  canBeSpread: boolean
}> = {
  'half-title': {
    name: 'Half Title',
    description: 'Simple page with just the book title',
    icon: 'Type',
    category: 'front-matter',
    defaultLayout: 'text-only',
    requiresImage: false,
    canBeSpread: false,
  },
  'frontispiece': {
    name: 'Frontispiece',
    description: 'Opening illustration facing the title page',
    icon: 'Image',
    category: 'front-matter',
    defaultLayout: 'image-only',
    requiresImage: true,
    canBeSpread: false,
  },
  'title-page': {
    name: 'Title Page',
    description: 'Full title, author, and illustrator',
    icon: 'BookOpen',
    category: 'front-matter',
    defaultLayout: 'text-only',
    requiresImage: false,
    canBeSpread: false,
  },
  'copyright': {
    name: 'Copyright',
    description: 'Copyright notice, ISBN, publisher info',
    icon: 'FileText',
    category: 'front-matter',
    defaultLayout: 'text-only',
    requiresImage: false,
    canBeSpread: false,
  },
  'dedication': {
    name: 'Dedication',
    description: 'Personal dedication message',
    icon: 'Heart',
    category: 'front-matter',
    defaultLayout: 'text-only',
    requiresImage: false,
    canBeSpread: false,
  },
  'blank': {
    name: 'Blank',
    description: 'Intentionally blank page',
    icon: 'Square',
    category: 'front-matter',
    defaultLayout: 'text-only',
    requiresImage: false,
    canBeSpread: false,
  },
  'story-single': {
    name: 'Story Page',
    description: 'Single page with illustration and text',
    icon: 'ImageIcon',
    category: 'story',
    defaultLayout: 'image-with-text',
    requiresImage: true,
    canBeSpread: false,
  },
  'story-spread': {
    name: 'Two-Page Spread',
    description: 'Illustration spanning two pages',
    icon: 'LayoutPanelLeft',
    category: 'story',
    defaultLayout: 'image-only',
    requiresImage: true,
    canBeSpread: true,
  },
  'the-end': {
    name: 'The End',
    description: 'Closing page with optional illustration',
    icon: 'Flag',
    category: 'back-matter',
    defaultLayout: 'image-with-text',
    requiresImage: false,
    canBeSpread: true,
  },
  'about-author': {
    name: 'About the Author',
    description: 'Author biography and photo',
    icon: 'User',
    category: 'back-matter',
    defaultLayout: 'text-only',
    requiresImage: false,
    canBeSpread: false,
  },
  'other-books': {
    name: 'Other Books',
    description: 'List of other books in series',
    icon: 'BookStack',
    category: 'back-matter',
    defaultLayout: 'text-only',
    requiresImage: false,
    canBeSpread: false,
  },
}

// KDP Page Count Options
// Amazon KDP requires minimum 24 interior pages for children's books
export type KDPPageCount = 24 | 28 | 32 | 36 | 40

export const KDP_PAGE_COUNTS: Array<{
  count: KDPPageCount
  name: string
  description: string
  storyPages: number
  frontMatterPages: number
  backMatterPages: number
  recommendedFor: string
}> = [
  {
    count: 24,
    name: '24 Pages (Minimum)',
    description: 'KDP minimum, ideal for ages 2-4',
    storyPages: 16,
    frontMatterPages: 6,
    backMatterPages: 2,
    recommendedFor: 'Simple stories, board book style',
  },
  {
    count: 28,
    name: '28 Pages',
    description: 'Standard picture book length',
    storyPages: 20,
    frontMatterPages: 6,
    backMatterPages: 2,
    recommendedFor: 'Most children\'s picture books',
  },
  {
    count: 32,
    name: '32 Pages (Most Common)',
    description: 'Industry standard for picture books',
    storyPages: 24,
    frontMatterPages: 6,
    backMatterPages: 2,
    recommendedFor: 'Traditional picture book format',
  },
  {
    count: 36,
    name: '36 Pages',
    description: 'Extended picture book',
    storyPages: 28,
    frontMatterPages: 6,
    backMatterPages: 2,
    recommendedFor: 'Longer stories, chapter books for early readers',
  },
  {
    count: 40,
    name: '40 Pages',
    description: 'Long-form picture book',
    storyPages: 32,
    frontMatterPages: 6,
    backMatterPages: 2,
    recommendedFor: 'Complex narratives, educational books',
  },
]

// Default front matter structure for KDP books
export const DEFAULT_FRONT_MATTER: Array<{
  pageType: PageType
  physicalPage: number
  required: boolean
}> = [
  { pageType: 'half-title', physicalPage: 1, required: true },
  { pageType: 'blank', physicalPage: 2, required: false },
  { pageType: 'title-page', physicalPage: 3, required: true },
  { pageType: 'copyright', physicalPage: 4, required: true },
  { pageType: 'dedication', physicalPage: 5, required: false },
  { pageType: 'blank', physicalPage: 6, required: false },
]

// Book format/aspect ratio
export type BookFormat = 'square' | 'landscape' | 'portrait' | 'wide'

// Page layout type
export type PageLayout =
  | 'image-with-text'      // Image fills page, text overlays
  | 'image-left-text-right' // Image on left page, text on right (spread)
  | 'text-left-image-right' // Text on left page, image on right (spread)
  | 'image-only'           // Full bleed image, no text
  | 'text-only'            // Text page with decorative border

// Book format configurations
// Based on Amazon KDP-compliant trim sizes for children's books
// Reference: https://kdp.amazon.com/en_US/help/topic/G201834180
export const BOOK_FORMATS: Record<BookFormat, {
  name: string
  description: string
  aspectRatio: string
  dimensions: string
  wordsPerPage: { min: number; max: number }
  bestFor: string
}> = {
  square: {
    name: 'Square',
    description: 'Classic picture book format (KDP)',
    aspectRatio: '1:1',
    dimensions: '8.5" x 8.5"',
    wordsPerPage: { min: 20, max: 50 },
    bestFor: 'Bedtime stories, character-focused tales'
  },
  landscape: {
    name: 'Landscape',
    description: 'Vertical format for scenic illustrations (KDP)',
    aspectRatio: '7:10',
    dimensions: '7" x 10"',
    wordsPerPage: { min: 25, max: 60 },
    bestFor: 'Adventure stories, nature scenes'
  },
  portrait: {
    name: 'Portrait',
    description: 'Traditional picture book format (KDP)',
    aspectRatio: '4:5',
    dimensions: '8" x 10"',
    wordsPerPage: { min: 30, max: 70 },
    bestFor: 'Character stories, fairy tales'
  },
  wide: {
    name: 'Wide Panoramic',
    description: 'Panoramic landscape format (KDP)',
    aspectRatio: '11:8',
    dimensions: '8.25" x 6"',
    wordsPerPage: { min: 15, max: 40 },
    bestFor: 'Action scenes, environmental storytelling'
  }
}

// Page layout configurations
export const PAGE_LAYOUTS: Record<PageLayout, {
  name: string
  description: string
  icon: string
}> = {
  'image-with-text': {
    name: 'Image + Text',
    description: 'Text overlaid on illustration',
    icon: 'ImageIcon'
  },
  'image-left-text-right': {
    name: 'Image | Text',
    description: 'Image on left, text on right',
    icon: 'LayoutPanelLeft'
  },
  'text-left-image-right': {
    name: 'Text | Image',
    description: 'Text on left, image on right',
    icon: 'LayoutPanelRight'
  },
  'image-only': {
    name: 'Full Image',
    description: 'Full bleed illustration',
    icon: 'Image'
  },
  'text-only': {
    name: 'Text Only',
    description: 'Decorative text page',
    icon: 'Type'
  }
}

// Wizard step - expanded for educational flow
// Original flow: story -> style -> characters -> pages -> preview
// New flow: character-setup -> category -> topic -> story-structure -> settings -> approach -> review -> style -> characters -> pages -> preview
export type WizardStep =
  | 'character-setup'  // NEW: Name, age, photo
  | 'category'         // NEW: Select educational category
  | 'topic'            // NEW: Select specific topic
  | 'story-structure'  // NEW: Select narrative structure (Story Spine, Hero's Journey, etc.)
  | 'settings'         // NEW: Page count, sentences per page
  | 'approach'         // NEW: Choose from 4 story ideas
  | 'review'           // NEW: Review generated story
  | 'story'            // EXISTING: For "paste your own" mode
  | 'style'            // EXISTING: Art style selection
  | 'characters'       // EXISTING: Character sheets
  | 'pages'            // EXISTING: Page generation
  | 'preview'          // EXISTING: Final preview

// Story creation mode
export type StoryMode = 'generate' | 'paste'

// Character role types for story characters added at setup
export type CharacterRole = 'sibling' | 'friend' | 'pet' | 'grandparent' | 'parent' | 'teacher' | 'other'

// Story character (added at setup, before story generation)
export interface StoryCharacter {
  id: string
  name: string
  role: CharacterRole
  relationship?: string  // e.g., "Emma's little brother", "Best friend"
  age?: number
  photoUrl?: string
  description?: string  // If no photo: "A fluffy golden retriever"
  characterSheetUrl?: string  // Generated character sheet (for consistency in page generation)
}

// API input type for story characters (without id)
export type StoryCharacterInput = Omit<StoryCharacter, 'id'>

// Role configurations for UI
export const CHARACTER_ROLES: Array<{
  id: CharacterRole
  name: string
  icon: string
  placeholder: string
}> = [
  { id: 'sibling', name: 'Sibling', icon: '👧', placeholder: "e.g., Emma's little brother" },
  { id: 'friend', name: 'Best Friend', icon: '🤝', placeholder: "e.g., School friend" },
  { id: 'pet', name: 'Pet', icon: '🐕', placeholder: "e.g., A fluffy golden retriever" },
  { id: 'grandparent', name: 'Grandparent', icon: '👴', placeholder: "e.g., Grandma who loves baking" },
  { id: 'parent', name: 'Parent', icon: '👨', placeholder: "e.g., Dad who works at the fire station" },
  { id: 'teacher', name: 'Teacher', icon: '👩‍🏫', placeholder: "e.g., Kind kindergarten teacher" },
  { id: 'other', name: 'Other', icon: '✨', placeholder: "Describe the character" },
]

// Character in a scene
export interface SceneCharacter {
  name: string // @CharacterName format
  expression: CharacterExpression
  pose?: string
  target?: string // Another @CharacterName they're interacting with
  position: CharacterPosition
}

// Scene JSON format for image generation
export interface SceneJSON {
  scene: {
    location: string
    mood?: string
    lighting?: string
    timeOfDay?: string
  }
  characters: SceneCharacter[]
  camera: {
    shot: CameraShot
    angle: CameraAngle
  }
}

// Text box positioning for draggable text
export interface TextBoxPosition {
  x: number // X coordinate in pixels (or percentage)
  y: number // Y coordinate in pixels (or percentage)
  width: number // Width in pixels (or percentage)
  height: number // Height in pixels (or percentage)
}

// A single page in the storybook
export interface StorybookPage {
  id: string
  pageNumber: number
  text: string // The story text for this page (plain text for TTS)
  richText?: string // Rich formatted text with HTML (bold, colors, fonts)
  textBoxPosition?: TextBoxPosition // Draggable text box coordinates (x, y, width, height)
  sceneJSON?: SceneJSON // Parsed scene (generated automatically)
  imageUrl?: string // Generated page image (single final image)
  // DEPRECATED: Grid-based variation system (removed in favor of recipe-based single image generation)
  // These fields are kept for backward compatibility with existing projects
  gridImageUrl?: string // DEPRECATED: The 3x3 grid image before frame extraction
  variationUrls?: string[] // DEPRECATED: All 9 variations (extracted from grid)
  selectedVariationIndex?: number // DEPRECATED: Which variation was selected (0-8)
  textPosition: TextPosition
  audioUrl?: string // Generated narration audio URL
  layout?: PageLayout // How text and image are arranged
  isSpread?: boolean // True if this page spans two physical pages

  // Extended page type support (Phase 2 - KDP compliance)
  pageType?: PageType // Type of page (story-single, title-page, etc.)
  spreadTextPosition?: SpreadTextPosition // Where text appears on a spread
  physicalPageNumbers?: number[] // Physical page numbers [7, 8] for spread
  beatId?: string // Reference to story structure beat (if applicable)
  isFrontMatter?: boolean // True if this is a front matter page
  isBackMatter?: boolean // True if this is a back matter page
}

// A character in the storybook
export interface StorybookCharacter {
  id: string
  name: string // Display name
  tag: string // @name format for prompts
  sourcePhotoUrl?: string // Original photo (if created from photo)
  characterSheetUrl?: string // Generated character sheet
  artStyle?: string // The style used for this character
  isFromLibrary?: boolean // Whether loaded from saved library
  description?: string // Visual description for character (used when no photo)
}

// Style guide for the storybook
export interface StorybookStyle {
  id: string
  name: string
  description?: string // Style description
  styleGuideUrl?: string // Generated or uploaded style guide image
  previewUrl?: string // Preview thumbnail (same as styleGuideUrl usually)
  sourceImageUrl?: string // Source image used to create style
  isPreset?: boolean // Whether it's a preset style
  presetId?: string // ID of the preset if applicable
}

// Main storybook project
// Recipe configuration for storybook generation
export interface StorybookRecipeConfig {
  styleGuideRecipeId?: string      // Recipe for generating style guides
  characterSheetRecipeId?: string  // Recipe for generating character sheets
  pageFirstRecipeId?: string       // Recipe for first pages
  pageContinuationRecipeId?: string // Recipe for continuation pages
  bookCoverRecipeId?: string       // Recipe for book covers
}

export interface StorybookProject {
  id: string
  title: string
  author?: string // Author name for book cover
  storyText: string // Full story text
  pages: StorybookPage[] // LEGACY: flat page array (kept for backward compatibility)
  characters: StorybookCharacter[]
  style?: StorybookStyle
  coverImageUrl?: string
  titlePageImageUrl?: string  // Interior title page illustration
  status: 'draft' | 'in-progress' | 'completed'
  creditsUsed: number
  createdAt: Date
  updatedAt: Date
  expiresAt?: Date // 30 days from creation
  // Book format settings
  bookFormat: BookFormat // square, landscape, portrait, wide
  defaultLayout: PageLayout // Default layout for new pages
  targetAge: number // Target reader age (3-12)
  // Recipe configuration (NEW)
  recipeConfig?: StorybookRecipeConfig

  // ==========================================================================
  // BEATS → SPREADS → PAGES ARCHITECTURE (NEW)
  // ==========================================================================
  // Primary data structures for KDP publishing pipeline
  beats?: StoryBeat[]           // AI-generated story moments (1 beat = 1 spread)
  spreads?: BookSpread[]        // User-designed layouts (2 facing pages each)
  // Physical pages are derived from spreads during PDF export

  // Education mode settings (NEW)
  storyMode: StoryMode // 'generate' or 'paste'
  // Main character (for generate mode)
  mainCharacterName?: string
  mainCharacterAge?: number
  mainCharacterPhotoUrl?: string // DEPRECATED: No longer used in UI, kept for backward compatibility
  // Additional story characters (siblings, friends, pets, etc.)
  storyCharacters?: StoryCharacter[]
  // Educational category and topic
  educationCategory?: string // e.g., 'math', 'narrative', 'reading'
  educationTopic?: string // e.g., 'counting-10', 'honesty'
  // Story structure (narrative framework)
  storyStructureId?: string // e.g., 'story-spine', 'heros-journey'
  // Book configuration
  pageCount?: number // 12, 24, 28, or 32 story pages
  sentencesPerPage?: number // 1-6

  // KDP Extended Book Configuration (Phase 2)
  kdpPageCount?: KDPPageCount // 24, 28, 32, 36, 40 (for print-ready books)
  includeFrontMatter?: boolean // Whether to generate front matter pages
  includeBackMatter?: boolean // Whether to generate back matter pages
  dedicationText?: string // Text for dedication page
  aboutAuthorText?: string // Text for about author page
  authorPhotoUrl?: string // Photo URL for about author page
  copyrightYear?: number // Year for copyright page
  publisherName?: string // Publisher name for copyright page
  isbnPlaceholder?: string // ISBN placeholder text
  // Customization options (NEW - Parent Power Features)
  storySetting?: string // e.g., 'park', 'beach', 'fantasy-castle'
  customSetting?: string // Free-text custom setting
  customElements?: string[] // e.g., ['dinosaurs', 'unicorns', 'magic']
  customNotes?: string // Free-text notes from parent
  // Story generation
  selectedApproach?: string // The approach ID selected by user
  selectedApproachTitle?: string
  selectedApproachSummary?: string
  generatedStory?: {
    title: string
    summary: string
    pages: Array<{
      pageNumber: number
      text: string
      sceneDescription: string
      learningNote?: string
    }>
  }
  // Extracted elements for reference images
  extractedCharacters?: Array<{
    name: string
    description: string
    appearances: number[]
    role: 'main' | 'supporting'
    photoUrl?: string
  }>
  extractedLocations?: Array<{
    name: string
    description: string
    appearances: number[]
  }>

  // Recipe references (system recipes used for generation)
  styleGuideRecipeId?: string // Recipe used for style guide generation
  characterSheetRecipeId?: string // Recipe used for character sheet generation
  pageRecipeId?: string // Recipe used for page illustration generation
}

// Wizard state
export interface WizardState {
  currentStep: WizardStep
  project: StorybookProject | null
  isGenerating: boolean
  error: string | null
}

// Step info for UI
export interface StepInfo {
  id: WizardStep
  label: string
  description: string
  backgroundImage: string
  icon: string
}

// Step configuration for GENERATE mode (educational flow)
// Background images feature diverse children in whimsical watercolor illustrations
export const GENERATE_WIZARD_STEPS: StepInfo[] = [
  {
    id: 'character-setup',
    label: 'Main Character',
    description: 'Create your main character',
    backgroundImage: '/storybook/step-character.webp', // Black girl + Asian boy reading in treehouse
    icon: 'User',
  },
  {
    id: 'category',
    label: 'Category',
    description: 'What should they learn?',
    backgroundImage: '/storybook/step-category.webp', // Diverse kids exploring with telescope/magnifying glass
    icon: 'Grid3X3',
  },
  {
    id: 'topic',
    label: 'Topic',
    description: 'Pick a specific topic',
    backgroundImage: '/storybook/step-topic.webp', // Black girl with braids discovering forest animals
    icon: 'Target',
  },
  {
    id: 'story-structure',
    label: 'Structure',
    description: 'Choose your story style',
    backgroundImage: '/storybook/step-approach.webp', // Reuse approach image for now
    icon: 'Workflow',
  },
  {
    id: 'settings',
    label: 'Settings',
    description: 'Configure your book',
    backgroundImage: '/storybook/step-settings.webp', // Mixed-race child at magical desk
    icon: 'Settings',
  },
  {
    id: 'approach',
    label: 'Approach',
    description: 'Choose your story idea',
    backgroundImage: '/storybook/step-approach.webp', // Asian girl + Black boy brainstorming ideas
    icon: 'Lightbulb',
  },
  {
    id: 'review',
    label: 'Review',
    description: 'Edit your story',
    backgroundImage: '/storybook/step-review.webp', // Black girl reading glowing book
    icon: 'FileText',
  },
  {
    id: 'style',
    label: 'Style',
    description: 'Choose your art style',
    backgroundImage: '/storybook/step-style.webp', // Diverse children painting at easels
    icon: 'Palette',
  },
  {
    id: 'characters',
    label: 'Characters',
    description: 'Create character sheets',
    backgroundImage: '/storybook/step-characters-new.webp', // Black boy designing character on tablet
    icon: 'Users',
  },
  {
    id: 'pages',
    label: 'Pages',
    description: 'Generate page illustrations',
    backgroundImage: '/storybook/step-pages.webp', // Asian girl + mixed-race boy with flying pages
    icon: 'Images',
  },
  {
    id: 'preview',
    label: 'Preview',
    description: 'Review and export',
    backgroundImage: '/storybook/step-preview.webp', // Diverse group holding finished storybook
    icon: 'BookCheck',
  },
]

// Step configuration for PASTE mode (original flow)
// Background images feature diverse children in whimsical watercolor illustrations
export const PASTE_WIZARD_STEPS: StepInfo[] = [
  {
    id: 'story',
    label: 'Story',
    description: 'Write or paste your story',
    backgroundImage: '/storybook/step-review.webp', // Black girl reading glowing book
    icon: 'BookOpen',
  },
  {
    id: 'style',
    label: 'Style',
    description: 'Choose your art style',
    backgroundImage: '/storybook/step-style.webp', // Diverse children painting at easels
    icon: 'Palette',
  },
  {
    id: 'characters',
    label: 'Characters',
    description: 'Create character sheets',
    backgroundImage: '/storybook/step-characters-new.webp', // Black boy designing character on tablet
    icon: 'Users',
  },
  {
    id: 'pages',
    label: 'Pages',
    description: 'Generate page illustrations',
    backgroundImage: '/storybook/step-pages.webp', // Asian girl + mixed-race boy with flying pages
    icon: 'Images',
  },
  {
    id: 'preview',
    label: 'Preview',
    description: 'Review and export',
    backgroundImage: '/storybook/step-preview.webp', // Diverse group holding finished storybook
    icon: 'BookCheck',
  },
]

// Legacy alias for backwards compatibility
export const WIZARD_STEPS = PASTE_WIZARD_STEPS

// Get steps for a given mode
export function getWizardSteps(mode: StoryMode): StepInfo[] {
  return mode === 'generate' ? GENERATE_WIZARD_STEPS : PASTE_WIZARD_STEPS
}

// Get step index for a mode
export function getStepIndex(step: WizardStep, mode: StoryMode = 'paste'): number {
  const steps = getWizardSteps(mode)
  return steps.findIndex(s => s.id === step)
}

// Get next step for a mode
export function getNextStep(step: WizardStep, mode: StoryMode = 'paste'): WizardStep | null {
  const steps = getWizardSteps(mode)
  const index = steps.findIndex(s => s.id === step)
  if (index >= 0 && index < steps.length - 1) {
    return steps[index + 1].id
  }
  return null
}

// Get previous step for a mode
export function getPreviousStep(step: WizardStep, mode: StoryMode = 'paste'): WizardStep | null {
  const steps = getWizardSteps(mode)
  const index = steps.findIndex(s => s.id === step)
  if (index > 0) {
    return steps[index - 1].id
  }
  return null
}
